"""drop_novelty_columns

Revision ID: dbeff360c330
Revises: 003_add_novelty_fields
Create Date: 2026-02-20 04:41:33.032207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbeff360c330'
down_revision: Union[str, None] = '003_add_novelty_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_embedding_ivfflat', table_name='document_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_chunks_document_index', table_name='document_chunks')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_user_status', table_name='documents')
    op.drop_index('idx_sessions_document_id', table_name='generation_sessions')
    op.drop_index('idx_sessions_user_id', table_name='generation_sessions')
    op.drop_index('idx_questions_document_id', table_name='questions')
    op.drop_index('idx_questions_generated_at', table_name='questions')
    op.drop_index('idx_questions_subject_id', table_name='questions')
    op.drop_index('idx_questions_vetting_status', table_name='questions', postgresql_where='(is_archived = false)')
    op.drop_column('users', 'max_regeneration_attempts')
    op.drop_column('users', 'novelty_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('novelty_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('max_regeneration_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('idx_questions_vetting_status', 'questions', ['vetting_status'], unique=False, postgresql_where='(is_archived = false)')
    op.create_index('idx_questions_subject_id', 'questions', ['subject_id'], unique=False)
    op.create_index('idx_questions_generated_at', 'questions', [sa.text('generated_at DESC')], unique=False)
    op.create_index('idx_questions_document_id', 'questions', ['document_id'], unique=False)
    op.create_index('idx_sessions_user_id', 'generation_sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_document_id', 'generation_sessions', ['document_id'], unique=False)
    op.create_index('idx_documents_user_status', 'documents', ['user_id', 'processing_status'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('idx_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_embedding_ivfflat', 'document_chunks', ['chunk_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
