"""add_session_subject_fields

Revision ID: e3871e9f4ef3
Revises: dbeff360c330
Create Date: 2026-02-20 06:25:33.586765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3871e9f4ef3'
down_revision: Union[str, None] = 'dbeff360c330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_embedding_ivfflat', table_name='document_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_chunks_document_index', table_name='document_chunks')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_user_status', table_name='documents')
    op.add_column('generation_sessions', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.add_column('generation_sessions', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.add_column('generation_sessions', sa.Column('generation_method', sa.String(length=20), nullable=True))
    op.alter_column('generation_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_sessions_document_id', table_name='generation_sessions')
    op.drop_index('idx_sessions_user_id', table_name='generation_sessions')
    op.drop_constraint('generation_sessions_document_id_fkey', 'generation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'generation_sessions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_sessions', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_sessions', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_questions_document_id', table_name='questions')
    op.drop_index('idx_questions_generated_at', table_name='questions')
    op.drop_index('idx_questions_subject_id', table_name='questions')
    op.drop_index('idx_questions_vetting_status', table_name='questions', postgresql_where='(is_archived = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_questions_vetting_status', 'questions', ['vetting_status'], unique=False, postgresql_where='(is_archived = false)')
    op.create_index('idx_questions_subject_id', 'questions', ['subject_id'], unique=False)
    op.create_index('idx_questions_generated_at', 'questions', [sa.text('generated_at DESC')], unique=False)
    op.create_index('idx_questions_document_id', 'questions', ['document_id'], unique=False)
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.create_foreign_key('generation_sessions_document_id_fkey', 'generation_sessions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_sessions_user_id', 'generation_sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_document_id', 'generation_sessions', ['document_id'], unique=False)
    op.alter_column('generation_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('generation_sessions', 'generation_method')
    op.drop_column('generation_sessions', 'topic_id')
    op.drop_column('generation_sessions', 'subject_id')
    op.create_index('idx_documents_user_status', 'documents', ['user_id', 'processing_status'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('idx_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_embedding_ivfflat', 'document_chunks', ['chunk_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
