"""add_session_subject_fields

Revision ID: e3871e9f4ef3
Revises: dbeff360c330
Create Date: 2026-02-20 06:25:33.586765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3871e9f4ef3'
down_revision: Union[str, None] = 'dbeff360c330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = inspector.get_columns(table_name)
    return any(col["name"] == column_name for col in columns)


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = inspector.get_foreign_keys(table_name)
    return any(fk.get("name") == constraint_name for fk in fks)


def _table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    op.execute('DROP INDEX IF EXISTS idx_chunk_embedding_ivfflat')
    op.execute('DROP INDEX IF EXISTS idx_chunks_document_id')
    op.execute('DROP INDEX IF EXISTS idx_chunks_document_index')
    op.execute('DROP INDEX IF EXISTS idx_documents_user_id')
    op.execute('DROP INDEX IF EXISTS idx_documents_user_status')

    if not _column_exists('generation_sessions', 'subject_id'):
        op.add_column('generation_sessions', sa.Column('subject_id', sa.String(length=36), nullable=True))
    if not _column_exists('generation_sessions', 'topic_id'):
        op.add_column('generation_sessions', sa.Column('topic_id', sa.String(length=36), nullable=True))
    if not _column_exists('generation_sessions', 'generation_method'):
        op.add_column('generation_sessions', sa.Column('generation_method', sa.String(length=20), nullable=True))

    op.alter_column('generation_sessions', 'document_id', nullable=True)

    op.execute('DROP INDEX IF EXISTS idx_sessions_document_id')
    op.execute('DROP INDEX IF EXISTS idx_sessions_user_id')

    if _constraint_exists('generation_sessions', 'generation_sessions_document_id_fkey'):
        op.drop_constraint('generation_sessions_document_id_fkey', 'generation_sessions', type_='foreignkey')

    if not _constraint_exists('generation_sessions', 'generation_sessions_subject_id_fkey'):
        op.create_foreign_key(
            'generation_sessions_subject_id_fkey',
            'generation_sessions',
            'subjects',
            ['subject_id'],
            ['id'],
            ondelete='SET NULL',
        )
    if _table_exists('topics') and not _constraint_exists('generation_sessions', 'generation_sessions_topic_id_fkey'):
        op.create_foreign_key(
            'generation_sessions_topic_id_fkey',
            'generation_sessions',
            'topics',
            ['topic_id'],
            ['id'],
            ondelete='SET NULL',
        )
    if not _constraint_exists('generation_sessions', 'generation_sessions_document_id_fkey'):
        op.create_foreign_key(
            'generation_sessions_document_id_fkey',
            'generation_sessions',
            'documents',
            ['document_id'],
            ['id'],
            ondelete='SET NULL',
        )

    op.execute('DROP INDEX IF EXISTS idx_questions_document_id')
    op.execute('DROP INDEX IF EXISTS idx_questions_generated_at')
    op.execute('DROP INDEX IF EXISTS idx_questions_subject_id')
    op.execute('DROP INDEX IF EXISTS idx_questions_vetting_status')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_questions_vetting_status', 'questions', ['vetting_status'], unique=False, postgresql_where='(is_archived = false)')
    if _column_exists('questions', 'subject_id'):
        op.create_index('idx_questions_subject_id', 'questions', ['subject_id'], unique=False)
    op.create_index('idx_questions_generated_at', 'questions', [sa.text('generated_at DESC')], unique=False)
    op.create_index('idx_questions_document_id', 'questions', ['document_id'], unique=False)
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.create_foreign_key('generation_sessions_document_id_fkey', 'generation_sessions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_sessions_user_id', 'generation_sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_document_id', 'generation_sessions', ['document_id'], unique=False)
    op.alter_column('generation_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('generation_sessions', 'generation_method')
    op.drop_column('generation_sessions', 'topic_id')
    op.drop_column('generation_sessions', 'subject_id')
    op.create_index('idx_documents_user_status', 'documents', ['user_id', 'processing_status'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('idx_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_embedding_ivfflat', 'document_chunks', ['chunk_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
