"""
Vetter Portal API endpoints.

These endpoints are dedicated to vetters who review and approve questions
generated by teachers. Vetters can view questions across all teachers,
filtered by subject and topic.
"""

import uuid
from typing import Optional, List
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy import select, func, and_, or_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload, joinedload
from pydantic import BaseModel, Field

from app.core.database import get_db
from app.api.v1.deps import get_current_vetter
from app.models.user import User
from app.models.question import Question
from app.models.subject import Subject, Topic
from app.services.question_service import QuestionGenerationService
from app.services.embedding_service import EmbeddingService
from app.schemas.question import QuestionSourceInfo, SourceReference


router = APIRouter()


# ============== Schemas ==============


class TeacherSummary(BaseModel):
    """Summary of a teacher for vetting."""
    id: uuid.UUID
    username: str
    full_name: Optional[str]
    email: str
    pending_count: int
    approved_count: int
    rejected_count: int
    subjects: List[str]
    
    model_config = {"from_attributes": True}


class SubjectSummary(BaseModel):
    """Summary of a subject for vetting."""
    id: uuid.UUID
    name: str
    code: str
    teacher_id: uuid.UUID
    teacher_name: str
    pending_count: int
    approved_count: int
    rejected_count: int
    topics: List[dict]
    
    model_config = {"from_attributes": True}


class TopicQuestionStats(BaseModel):
    """Stats for topics."""
    id: uuid.UUID
    name: str
    pending_count: int
    approved_count: int
    rejected_count: int


class VetterDashboard(BaseModel):
    """Dashboard data for vetters."""
    total_pending: int
    total_approved: int
    total_rejected: int
    teachers_with_pending: int
    subjects_with_pending: int
    recent_submissions: int  # Last 24 hours


class VetterQuestionFilters(BaseModel):
    """Filters for vetter question list."""
    teacher_id: Optional[uuid.UUID] = None
    subject_id: Optional[uuid.UUID] = None
    topic_id: Optional[uuid.UUID] = None
    question_type: Optional[str] = None
    status: Optional[str] = "pending"  # pending, approved, rejected, all
    from_date: Optional[datetime] = None
    to_date: Optional[datetime] = None


class QuestionForVetting(BaseModel):
    """Question data for vetting UI."""
    id: uuid.UUID
    question_text: str
    question_type: str
    options: Optional[List[str]]
    correct_answer: Optional[str]
    explanation: Optional[str]
    marks: Optional[int]
    difficulty_level: Optional[str]
    bloom_taxonomy_level: Optional[str]
    vetting_status: str
    vetting_notes: Optional[str]
    learning_outcome_id: Optional[str]
    course_outcome_mapping: Optional[dict]
    generated_at: datetime
    
    # Teacher info
    teacher_id: Optional[uuid.UUID]
    teacher_name: Optional[str]
    
    # Subject/Topic info
    subject_id: Optional[uuid.UUID]
    subject_name: Optional[str]
    subject_code: Optional[str]
    topic_id: Optional[uuid.UUID]
    topic_name: Optional[str]
    source_info: Optional[QuestionSourceInfo] = None

    # Version control
    version_number: int = 1
    replaces_id: Optional[uuid.UUID] = None
    replaced_by_id: Optional[uuid.UUID] = None

    model_config = {"from_attributes": True}


class VetQuestionRequest(BaseModel):
    """Request to vet a question."""
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None
    course_outcome_mapping: Optional[dict] = None
    rejection_reasons: Optional[List[str]] = None
    custom_feedback: Optional[str] = None


class BulkVetRequest(BaseModel):
    """Request to vet multiple questions at once."""
    question_ids: List[uuid.UUID]
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None


# ============== Dashboard ==============


@router.get("/dashboard", response_model=VetterDashboard)
async def get_vetter_dashboard(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get vetter dashboard with aggregate stats across all teachers.
    """
    # Count pending questions
    pending_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_pending = pending_result.scalar() or 0
    
    # Count approved questions
    approved_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "approved",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_approved = approved_result.scalar() or 0
    
    # Count rejected questions
    rejected_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "rejected",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_rejected = rejected_result.scalar() or 0
    
    # Count teachers with pending questions
    teachers_result = await db.execute(
        select(func.count(func.distinct(Subject.user_id))).where(
            Subject.id.in_(
                select(Question.subject_id).where(
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                    Question.subject_id.isnot(None),
                )
            )
        )
    )
    teachers_with_pending = teachers_result.scalar() or 0
    
    # Count subjects with pending questions
    subjects_result = await db.execute(
        select(func.count(func.distinct(Question.subject_id))).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
            Question.subject_id.isnot(None),
        )
    )
    subjects_with_pending = subjects_result.scalar() or 0
    
    # Count recent submissions (last 24 hours)
    yesterday = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    recent_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.generated_at >= yesterday,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    recent_submissions = recent_result.scalar() or 0
    
    return VetterDashboard(
        total_pending=total_pending,
        total_approved=total_approved,
        total_rejected=total_rejected,
        teachers_with_pending=teachers_with_pending,
        subjects_with_pending=subjects_with_pending,
        recent_submissions=recent_submissions,
    )


# ============== Teachers List ==============


@router.get("/teachers", response_model=List[TeacherSummary])
async def get_teachers_with_questions(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of teachers who have generated questions, with stats.
    """
    # Get distinct teachers who have subjects with questions
    query = """
        SELECT 
            u.id,
            u.username,
            u.full_name,
            u.email,
            COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
            array_agg(DISTINCT s.name) FILTER (WHERE s.name IS NOT NULL) as subjects
        FROM users u
        JOIN subjects s ON s.user_id = u.id
        LEFT JOIN questions q ON q.subject_id = s.id
        WHERE u.role = 'teacher'
        GROUP BY u.id, u.username, u.full_name, u.email
        HAVING COUNT(q.id) > 0
        ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
    """
    
    from sqlalchemy import text
    result = await db.execute(text(query))
    rows = result.fetchall()
    
    teachers = []
    for row in rows:
        teachers.append(TeacherSummary(
            id=row[0],
            username=row[1],
            full_name=row[2],
            email=row[3],
            pending_count=row[4] or 0,
            approved_count=row[5] or 0,
            rejected_count=row[6] or 0,
            subjects=row[7] or [],
        ))
    
    return teachers


# ============== Subjects List ==============


@router.get("/subjects", response_model=List[SubjectSummary])
async def get_subjects_with_questions(
    teacher_id: Optional[uuid.UUID] = Query(None, description="Filter by teacher"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of subjects with question stats, optionally filtered by teacher.
    """
    from sqlalchemy import text
    
    base_query = """
        SELECT 
            s.id,
            s.name,
            s.code,
            s.user_id as teacher_id,
            u.full_name as teacher_name,
            COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count
        FROM subjects s
        JOIN users u ON u.id = s.user_id
        LEFT JOIN questions q ON q.subject_id = s.id
    """
    
    if teacher_id:
        base_query += f" WHERE s.user_id = '{teacher_id}'"
    
    base_query += """
        GROUP BY s.id, s.name, s.code, s.user_id, u.full_name
        HAVING COUNT(q.id) > 0
        ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
    """
    
    result = await db.execute(text(base_query))
    rows = result.fetchall()
    
    subjects = []
    for row in rows:
        subject_id = row[0]
        
        # Get topics for this subject
        topics_result = await db.execute(
            select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
        )
        topics = topics_result.scalars().all()
        
        # Get topic stats
        topic_stats = []
        for topic in topics:
            topic_pending = await db.execute(
                select(func.count(Question.id)).where(
                    Question.topic_id == topic.id,
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                )
            )
            topic_stats.append({
                "id": str(topic.id),
                "name": topic.name,
                "pending_count": topic_pending.scalar() or 0,
            })
        
        subjects.append(SubjectSummary(
            id=row[0],
            name=row[1],
            code=row[2],
            teacher_id=row[3],
            teacher_name=row[4] or "Unknown",
            pending_count=row[5] or 0,
            approved_count=row[6] or 0,
            rejected_count=row[7] or 0,
            topics=topic_stats,
        ))
    
    return subjects


# ============== Questions List ==============


@router.get("/questions", response_model=dict)
async def get_questions_for_vetting(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    teacher_id: Optional[uuid.UUID] = Query(None),
    subject_id: Optional[uuid.UUID] = Query(None),
    topic_id: Optional[uuid.UUID] = Query(None),
    question_type: Optional[str] = Query(None),
    status: str = Query("pending", pattern="^(pending|approved|rejected|all)$"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get paginated list of questions for vetting.
    """
    # Build base query
    query = (
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    
    # Apply filters
    if status != "all":
        query = query.where(Question.vetting_status == status)
    
    if subject_id:
        query = query.where(Question.subject_id == subject_id)
    
    if topic_id:
        query = query.where(Question.topic_id == topic_id)
    
    if question_type:
        query = query.where(Question.question_type == question_type)
    
    # Filter by teacher (via subject ownership)
    if teacher_id:
        query = query.where(
            Question.subject_id.in_(
                select(Subject.id).where(Subject.user_id == teacher_id)
            )
        )
    
    # Get total count
    count_query = select(func.count()).select_from(query.subquery())
    total_result = await db.execute(count_query)
    total = total_result.scalar() or 0
    
    # Apply pagination
    offset = (page - 1) * limit
    query = query.order_by(Question.generated_at.desc()).offset(offset).limit(limit)
    
    result = await db.execute(query)
    questions = result.scalars().all()
    
    # Build response
    question_responses = []
    for q in questions:
        # Get teacher info from subject
        teacher_name = None
        teacher_id_val = None
        if q.subject:
            # Fetch teacher
            teacher_result = await db.execute(
                select(User).where(User.id == q.subject.user_id)
            )
            teacher = teacher_result.scalar_one_or_none()
            if teacher:
                teacher_name = teacher.full_name or teacher.username
                teacher_id_val = teacher.id
        
        # Extract source_info from generation_metadata
        source_info = None
        if q.generation_metadata:
            metadata = q.generation_metadata
            if "source_info" in metadata:
                source_info = QuestionSourceInfo(**metadata["source_info"])
            elif "sources" in metadata:
                source_info = QuestionSourceInfo(
                    sources=[SourceReference(**s) for s in metadata.get("sources", [])],
                    generation_reasoning=metadata.get("generation_reasoning"),
                    content_coverage=metadata.get("content_coverage"),
                )

        question_responses.append(QuestionForVetting(
            id=q.id,
            question_text=q.question_text,
            question_type=q.question_type,
            options=q.options,
            correct_answer=q.correct_answer,
            explanation=q.explanation,
            marks=q.marks,
            difficulty_level=q.difficulty_level,
            bloom_taxonomy_level=q.bloom_taxonomy_level,
            vetting_status=q.vetting_status,
            vetting_notes=q.vetting_notes,
            learning_outcome_id=q.learning_outcome_id,
            course_outcome_mapping=q.course_outcome_mapping,
            generated_at=q.generated_at,
            teacher_id=teacher_id_val,
            teacher_name=teacher_name,
            subject_id=q.subject_id,
            subject_name=q.subject.name if q.subject else None,
            subject_code=q.subject.code if q.subject else None,
            topic_id=q.topic_id,
            topic_name=q.topic.name if q.topic else None,
            source_info=source_info,
            version_number=q.version_number or 1,
            replaces_id=q.replaces_id,
            replaced_by_id=q.replaced_by_id,
        ))
    
    return {
        "questions": question_responses,
        "total": total,
        "page": page,
        "limit": limit,
        "pages": (total + limit - 1) // limit,
    }


# ============== Vet Question ==============


@router.post("/questions/{question_id}/vet")
async def vet_question(
    question_id: uuid.UUID,
    vet_data: VetQuestionRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject a question.
    """
    # Get question
    result = await db.execute(
        select(Question).where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()
    
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )
    
    # Update vetting status
    question.vetting_status = vet_data.status
    question.vetting_notes = vet_data.notes
    question.vetted_at = datetime.now(timezone.utc)
    question.vetted_by = current_user.id
    
    # Update CO mapping if provided
    if vet_data.course_outcome_mapping:
        question.course_outcome_mapping = vet_data.course_outcome_mapping
    
    # Store rejection reasons if rejected
    if vet_data.status == "rejected" and vet_data.rejection_reasons:
        question.vetting_notes = f"{vet_data.notes or ''}\nReasons: {', '.join(vet_data.rejection_reasons)}"
        if vet_data.custom_feedback:
            question.vetting_notes += f"\nFeedback: {vet_data.custom_feedback}"
    
    await db.commit()
    
    return {
        "message": f"Question {vet_data.status}",
        "question_id": str(question_id),
        "status": vet_data.status,
    }


# ============== Bulk Vet ==============


@router.post("/questions/bulk-vet")
async def bulk_vet_questions(
    bulk_data: BulkVetRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject multiple questions at once.
    """
    # Get questions
    result = await db.execute(
        select(Question).where(
            Question.id.in_(bulk_data.question_ids),
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    questions = result.scalars().all()
    
    if not questions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No questions found",
        )
    
    # Update all questions
    for question in questions:
        question.vetting_status = bulk_data.status
        question.vetting_notes = bulk_data.notes
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id
    
    await db.commit()
    
    return {
        "message": f"{len(questions)} questions {bulk_data.status}",
        "count": len(questions),
        "status": bulk_data.status,
    }


# ============== Topic Stats ==============


@router.get("/subjects/{subject_id}/topics", response_model=List[TopicQuestionStats])
async def get_topic_stats(
    subject_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get detailed topic stats for a subject.
    """
    # Verify subject exists
    subject_result = await db.execute(
        select(Subject).where(Subject.id == subject_id)
    )
    subject = subject_result.scalar_one_or_none()
    
    if not subject:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Subject not found",
        )
    
    # Get topics with stats
    topics_result = await db.execute(
        select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
    )
    topics = topics_result.scalars().all()
    
    stats = []
    for topic in topics:
        pending = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "pending",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        approved = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "approved",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        rejected = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "rejected",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        
        stats.append(TopicQuestionStats(
            id=topic.id,
            name=topic.name,
            pending_count=pending.scalar() or 0,
            approved_count=approved.scalar() or 0,
            rejected_count=rejected.scalar() or 0,
        ))
    
    return stats


# ============== Update Question (Vetter) ==============


class RejectAndRegenerateRequest(BaseModel):
    """Request to reject a question and trigger regeneration."""
    notes: Optional[str] = None
    rejection_reasons: Optional[List[str]] = None
    custom_feedback: Optional[str] = None


# ============== Reject and Regenerate ==============


@router.post("/questions/{question_id}/reject-and-regenerate")
async def reject_and_regenerate_question(
    question_id: uuid.UUID,
    vet_data: RejectAndRegenerateRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Reject a question and automatically regenerate a replacement.
    Creates a new GenerationSession (vetter_regen) linked to the teacher's account,
    so it appears in their history. The new question replaces the rejected one.
    """
    import logging
    import random
    from app.models.question import GenerationSession
    from app.models.document import DocumentChunk

    logger = logging.getLogger(__name__)

    # 1. Get the question with subject loaded
    result = await db.execute(
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()

    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )

    # 2. Build rejection notes
    rejection_notes = vet_data.notes or ""
    if vet_data.rejection_reasons:
        rejection_notes = f"{rejection_notes}\nReasons: {', '.join(vet_data.rejection_reasons)}".strip()
    if vet_data.custom_feedback:
        rejection_notes = f"{rejection_notes}\nFeedback: {vet_data.custom_feedback}".strip()

    # 3. Mark original as rejected and NOT latest
    question.vetting_status = "rejected"
    question.vetting_notes = rejection_notes or None
    question.vetted_at = datetime.now(timezone.utc)
    question.vetted_by = current_user.id
    question.is_latest = False

    # Get teacher's user_id from subject
    teacher_id = question.subject.user_id if question.subject else None
    document_id = question.document_id

    # 4. If document_id is null but subject_id exists, find any usable document for the subject
    if not document_id and question.subject_id:
        from app.models.document import Document
        doc_result = await db.execute(
            select(Document.id)
            .where(
                Document.subject_id == question.subject_id,
                Document.processing_status == "completed",
            )
            .order_by(Document.upload_timestamp.desc())
            .limit(1)
        )
        fallback_doc_id = doc_result.scalar_one_or_none()
        if fallback_doc_id:
            document_id = fallback_doc_id

    # 5. If still no document or no teacher, just reject (restore is_latest=True)
    if not document_id or not teacher_id:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (no document available for regeneration)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 5. Get document chunks (join document so _build_source_info can read filename)
    chunks_result = await db.execute(
        select(DocumentChunk)
        .options(joinedload(DocumentChunk.document))
        .where(DocumentChunk.document_id == document_id)
        .order_by(DocumentChunk.chunk_index)
    )
    chunks = chunks_result.scalars().all()

    if not chunks:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (no document content available for regeneration)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 6. Preload existing embeddings for subject-level dedupe
    existing_embeddings = []
    if question.subject_id:
        try:
            emb_res = await db.execute(
                select(Question.question_embedding).where(
                    Question.subject_id == question.subject_id,
                    Question.is_archived == False,
                    Question.question_embedding.isnot(None),
                ).limit(2000)
            )
            existing_embeddings = [r[0] for r in emb_res.all()]
            logger.info(f"reject_and_regenerate: Preloaded {len(existing_embeddings)} existing embeddings for dedupe")
        except Exception as e:
            logger.warning(f"reject_and_regenerate: Could not preload existing embeddings: {e}")

    # 7. Generate a replacement question (with dedupe retry loop)
    import numpy as np
    gen_service = QuestionGenerationService(db)
    embedding_service = EmbeddingService()
    question_data = None
    selected_chunks = chunks[:3]  # fallback; overwritten on each attempt
    REGEN_MAX_ATTEMPTS = 3
    for attempt in range(REGEN_MAX_ATTEMPTS):
        try:
            selected_chunks = random.sample(chunks, min(3, len(chunks)))
            candidate_data = await gen_service._generate_single_question(
                chunks=selected_chunks,
                question_type=question.question_type,
                difficulty=question.difficulty_level or "medium",
                marks=question.marks,
                bloom_levels=[question.bloom_taxonomy_level] if question.bloom_taxonomy_level else None,
            )
            if not candidate_data:
                continue

            # Embedding-based dedupe check
            if existing_embeddings:
                candidate_emb = await embedding_service.get_embedding(candidate_data["question_text"])
                q_vec = np.array(candidate_emb)
                matrix = np.array(existing_embeddings)
                q_norm = q_vec / (np.linalg.norm(q_vec) or 1.0)
                norms = np.linalg.norm(matrix, axis=1, keepdims=True)
                norms[norms == 0] = 1.0
                max_sim = float(np.max(np.dot(matrix / norms, q_norm)))
                if max_sim > 0.85:
                    logger.warning(f"reject_and_regenerate: attempt {attempt + 1} rejected as duplicate (sim={max_sim:.4f})")
                    continue

            question_data = candidate_data
            break
        except Exception as e:
            logger.error(f"reject_and_regenerate: generation attempt {attempt + 1} failed: {e}")

    if not question_data:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (could not generate non-duplicate replacement)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 7. Reuse the original question's session so the regen appears in the same history entry.
    #    If the question has no session (e.g. subject-level gen), create a new one as fallback.
    session_id_to_use = question.session_id
    if not session_id_to_use:
        fallback_session = GenerationSession(
            user_id=teacher_id,
            document_id=document_id,
            subject_id=question.subject_id,
            topic_id=question.topic_id,
            generation_method="vetter_regen",
            requested_count=1,
            status="completed",
            started_at=datetime.now(timezone.utc),
            completed_at=datetime.now(timezone.utc),
            questions_generated=1,
            generation_config={
                "vetted_by": str(current_user.id),
                "original_question_id": str(question_id),
            },
        )
        db.add(fallback_session)
        await db.flush()
        session_id_to_use = fallback_session.id
    # NOTE: Do NOT increment questions_generated — the vetter replacement is a 1-for-1 swap,
    # not a new generation. Bumping the count inflates the teacher's history totals.

    # 8. Save the new question
    try:
        new_question, _ = await gen_service._save_question(
            document_id=document_id,
            session_id=session_id_to_use,
            question_data=question_data,
            question_type=question.question_type,
            marks=question.marks,
            difficulty=question.difficulty_level or "medium",
            chunk_ids=[c.id for c in selected_chunks],
            chunks=selected_chunks,
            subject_id=question.subject_id,
            topic_id=question.topic_id,
        )
    except Exception as e:
        logger.error(f"reject_and_regenerate: save failed: {e}")
        await db.rollback()
        # Re-fetch and restore the original question
        fresh_result = await db.execute(select(Question).where(Question.id == question_id))
        fresh_q = fresh_result.scalar_one_or_none()
        if fresh_q:
            fresh_q.is_latest = True
            fresh_q.vetting_status = "rejected"
            fresh_q.vetted_at = datetime.now(timezone.utc)
            fresh_q.vetted_by = current_user.id
            fresh_q.vetting_notes = rejection_notes or None
            await db.commit()
        return {
            "message": "Question rejected (failed to save regenerated question)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 9. Link the new question as the replacement
    new_question.replaces_id = question_id
    new_question.version_number = (question.version_number or 1) + 1
    new_question.is_latest = True
    new_question.vetting_status = "pending"
    new_question.generation_metadata = {
        **(new_question.generation_metadata or {}),
        "regenerated_by_vetter": True,
        "original_question_id": str(question_id),
        "vetted_by": str(current_user.id),
    }

    # 10. Update replaced_by on the original (now done after we have new_question.id)
    question.replaced_by_id = new_question.id

    await db.commit()
    await db.refresh(new_question)

    logger.info(
        f"reject_and_regenerate: question {question_id} rejected by {current_user.id}, "
        f"new question {new_question.id} created for teacher {teacher_id}"
    )

    # Build source_info for the response from generation_metadata
    new_source_info = None
    gen_meta = new_question.generation_metadata or {}
    if "source_info" in gen_meta:
        meta_si = gen_meta["source_info"]
        if meta_si and meta_si.get("sources"):
            new_source_info = QuestionSourceInfo(
                sources=[SourceReference(**s) for s in meta_si["sources"]],
                generation_reasoning=meta_si.get("generation_reasoning"),
                content_coverage=meta_si.get("content_coverage"),
            ).model_dump()

    return {
        "message": "Question rejected and regenerated successfully",
        "question_id": str(question_id),
        "status": "rejected",
        "regenerated": True,
        "new_question": {
            "id": str(new_question.id),
            "question_text": new_question.question_text,
            "question_type": new_question.question_type,
            "options": new_question.options,
            "correct_answer": new_question.correct_answer,
            "marks": new_question.marks,
            "difficulty_level": new_question.difficulty_level,
            "bloom_taxonomy_level": new_question.bloom_taxonomy_level,
            "vetting_status": new_question.vetting_status,
            "version_number": new_question.version_number,
            "session_id": str(new_question.session_id),
            "source_info": new_source_info,
        },
    }


class VetterUpdateQuestionRequest(BaseModel):
    """Request body for vetter to update a question."""
    marks: Optional[int] = None
    difficulty_level: Optional[str] = None
    bloom_taxonomy_level: Optional[str] = None
    correct_answer: Optional[str] = None
    options: Optional[List[str]] = None
    question_text: Optional[str] = None
    course_outcome_mapping: Optional[dict] = None
    learning_outcome_id: Optional[str] = None


# ============== Version History ==============


@router.get("/questions/{question_id}/version-history")
async def get_question_version_history(
    question_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get all versions in a question's regeneration chain, ordered oldest-first.
    """
    import logging
    logger = logging.getLogger(__name__)

    # Ensure the question exists
    result = await db.execute(select(Question).where(Question.id == question_id))
    question = result.scalar_one_or_none()
    if not question:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")

    # Walk backwards to find the root version
    seen: set = set()
    current_q = question
    while current_q.replaces_id and current_q.replaces_id not in seen:
        seen.add(current_q.id)
        prev_result = await db.execute(select(Question).where(Question.id == current_q.replaces_id))
        prev_q = prev_result.scalar_one_or_none()
        if not prev_q:
            break
        current_q = prev_q

    # Walk forward from root to collect chain
    versions = []
    chain_seen: set = set()
    q = current_q
    while q and q.id not in chain_seen:
        chain_seen.add(q.id)
        versions.append(q)
        if not q.replaced_by_id:
            break
        next_result = await db.execute(select(Question).where(Question.id == q.replaced_by_id))
        q = next_result.scalar_one_or_none()

    return {
        "question_id": str(question_id),
        "versions": [
            {
                "id": str(v.id),
                "version_number": v.version_number or 1,
                "question_text": v.question_text,
                "question_type": v.question_type,
                "options": v.options,
                "correct_answer": v.correct_answer,
                "marks": v.marks,
                "difficulty_level": v.difficulty_level,
                "vetting_status": v.vetting_status,
                "vetting_notes": v.vetting_notes,
                "is_latest": v.is_latest,
                "generated_at": v.generated_at.isoformat() if v.generated_at else None,
            }
            for v in versions
        ],
    }


# ============== Restore Version ==============


@router.post("/questions/{question_id}/restore")
async def restore_question_version(
    question_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Restore a previous version by making it the latest active version.
    All other versions in the same chain are demoted to is_latest=False.
    The restored version's vetting_status is reset to 'pending'.
    """
    import logging
    logger = logging.getLogger(__name__)

    # Get the target version
    result = await db.execute(select(Question).where(Question.id == question_id))
    target = result.scalar_one_or_none()
    if not target:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question version not found")

    # Collect all chain IDs by walking backwards and forwards
    chain_ids: set = set()
    # Walk backwards
    current_q = target
    while current_q:
        chain_ids.add(current_q.id)
        if current_q.replaces_id and current_q.replaces_id not in chain_ids:
            prev_result = await db.execute(select(Question).where(Question.id == current_q.replaces_id))
            current_q = prev_result.scalar_one_or_none()
        else:
            break
    # Walk forwards from target
    current_q = target
    while current_q:
        chain_ids.add(current_q.id)
        if current_q.replaced_by_id and current_q.replaced_by_id not in chain_ids:
            next_result = await db.execute(select(Question).where(Question.id == current_q.replaced_by_id))
            current_q = next_result.scalar_one_or_none()
        else:
            break

    # Set all chain members to is_latest=False
    chain_result = await db.execute(select(Question).where(Question.id.in_(list(chain_ids))))
    for q in chain_result.scalars().all():
        q.is_latest = False

    # Promote the target version
    target.is_latest = True
    target.vetting_status = "pending"
    target.vetting_notes = f"Restored from version history by vetter"

    await db.commit()
    await db.refresh(target)
    logger.info(f"Question version {question_id} restored as latest by vetter {current_user.id}")

    return {
        "message": "Version restored successfully",
        "restored_question_id": str(question_id),
        "version_number": target.version_number or 1,
    }





@router.put("/questions/{question_id}", response_model=dict)
async def update_question_as_vetter(
    question_id: uuid.UUID,
    update_data: VetterUpdateQuestionRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Update a question as a vetter.
    Vetters can edit marks, difficulty, answers, and mappings.
    """
    # Get question
    result = await db.execute(
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()
    
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )
    
    # Update fields if provided
    if update_data.marks is not None:
        question.marks = update_data.marks
    if update_data.difficulty_level is not None:
        question.difficulty_level = update_data.difficulty_level
    if update_data.bloom_taxonomy_level is not None:
        question.bloom_taxonomy_level = update_data.bloom_taxonomy_level
    if update_data.correct_answer is not None:
        question.correct_answer = update_data.correct_answer
    if update_data.options is not None:
        question.options = update_data.options
    if update_data.question_text is not None:
        question.question_text = update_data.question_text
    if update_data.course_outcome_mapping is not None:
        question.course_outcome_mapping = update_data.course_outcome_mapping
    if update_data.learning_outcome_id is not None:
        question.learning_outcome_id = update_data.learning_outcome_id
    
    await db.commit()
    await db.refresh(question)
    
    return {
        "message": "Question updated successfully",
        "question_id": str(question_id),
        "question": {
            "id": str(question.id),
            "question_text": question.question_text,
            "question_type": question.question_type,
            "options": question.options,
            "correct_answer": question.correct_answer,
            "marks": question.marks,
            "difficulty_level": question.difficulty_level,
            "bloom_taxonomy_level": question.bloom_taxonomy_level,
            "course_outcome_mapping": question.course_outcome_mapping,
            "learning_outcome_id": question.learning_outcome_id,
            "vetting_status": question.vetting_status,
        },
    }
