"""
Vetter Portal API endpoints.

These endpoints are dedicated to vetters who review and approve questions
generated by teachers. Vetters can view questions across all teachers,
filtered by subject and topic.
"""

import uuid
from typing import Optional, List
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy import select, func, and_, or_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from pydantic import BaseModel, Field

from app.core.database import get_db
from app.api.v1.deps import get_current_vetter
from app.models.user import User
from app.models.question import Question
from app.models.subject import Subject, Topic
from app.services.question_service import QuestionGenerationService
from app.services.embedding_service import EmbeddingService


router = APIRouter()


# ============== Schemas ==============


class TeacherSummary(BaseModel):
    """Summary of a teacher for vetting."""
    id: uuid.UUID
    username: str
    full_name: Optional[str]
    email: str
    pending_count: int
    approved_count: int
    rejected_count: int
    subjects: List[str]
    
    model_config = {"from_attributes": True}


class SubjectSummary(BaseModel):
    """Summary of a subject for vetting."""
    id: uuid.UUID
    name: str
    code: str
    teacher_id: uuid.UUID
    teacher_name: str
    pending_count: int
    approved_count: int
    rejected_count: int
    topics: List[dict]
    
    model_config = {"from_attributes": True}


class TopicQuestionStats(BaseModel):
    """Stats for topics."""
    id: uuid.UUID
    name: str
    pending_count: int
    approved_count: int
    rejected_count: int


class VetterDashboard(BaseModel):
    """Dashboard data for vetters."""
    total_pending: int
    total_approved: int
    total_rejected: int
    teachers_with_pending: int
    subjects_with_pending: int
    recent_submissions: int  # Last 24 hours


class VetterQuestionFilters(BaseModel):
    """Filters for vetter question list."""
    teacher_id: Optional[uuid.UUID] = None
    subject_id: Optional[uuid.UUID] = None
    topic_id: Optional[uuid.UUID] = None
    question_type: Optional[str] = None
    status: Optional[str] = "pending"  # pending, approved, rejected, all
    from_date: Optional[datetime] = None
    to_date: Optional[datetime] = None


class QuestionForVetting(BaseModel):
    """Question data for vetting UI."""
    id: uuid.UUID
    question_text: str
    question_type: str
    options: Optional[List[str]]
    correct_answer: Optional[str]
    explanation: Optional[str]
    expected_answer: Optional[str]
    key_points: Optional[List[str]]
    marks: Optional[int]
    difficulty_level: Optional[str]
    bloom_taxonomy_level: Optional[str]
    vetting_status: str
    vetting_notes: Optional[str]
    learning_outcome_id: Optional[str]
    course_outcome_mapping: Optional[dict]
    created_at: datetime
    
    # Teacher info
    teacher_id: Optional[uuid.UUID]
    teacher_name: Optional[str]
    
    # Subject/Topic info
    subject_id: Optional[uuid.UUID]
    subject_name: Optional[str]
    subject_code: Optional[str]
    topic_id: Optional[uuid.UUID]
    topic_name: Optional[str]
    
    model_config = {"from_attributes": True}


class VetQuestionRequest(BaseModel):
    """Request to vet a question."""
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None
    course_outcome_mapping: Optional[dict] = None
    rejection_reasons: Optional[List[str]] = None
    custom_feedback: Optional[str] = None


class BulkVetRequest(BaseModel):
    """Request to vet multiple questions at once."""
    question_ids: List[uuid.UUID]
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None


# ============== Dashboard ==============


@router.get("/dashboard", response_model=VetterDashboard)
async def get_vetter_dashboard(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get vetter dashboard with aggregate stats across all teachers.
    """
    # Count pending questions
    pending_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_pending = pending_result.scalar() or 0
    
    # Count approved questions
    approved_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "approved",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_approved = approved_result.scalar() or 0
    
    # Count rejected questions
    rejected_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "rejected",
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    total_rejected = rejected_result.scalar() or 0
    
    # Count teachers with pending questions
    teachers_result = await db.execute(
        select(func.count(func.distinct(Subject.user_id))).where(
            Subject.id.in_(
                select(Question.subject_id).where(
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                    Question.subject_id.isnot(None),
                )
            )
        )
    )
    teachers_with_pending = teachers_result.scalar() or 0
    
    # Count subjects with pending questions
    subjects_result = await db.execute(
        select(func.count(func.distinct(Question.subject_id))).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
            Question.subject_id.isnot(None),
        )
    )
    subjects_with_pending = subjects_result.scalar() or 0
    
    # Count recent submissions (last 24 hours)
    yesterday = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    recent_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.created_at >= yesterday,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    recent_submissions = recent_result.scalar() or 0
    
    return VetterDashboard(
        total_pending=total_pending,
        total_approved=total_approved,
        total_rejected=total_rejected,
        teachers_with_pending=teachers_with_pending,
        subjects_with_pending=subjects_with_pending,
        recent_submissions=recent_submissions,
    )


# ============== Teachers List ==============


@router.get("/teachers", response_model=List[TeacherSummary])
async def get_teachers_with_questions(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of teachers who have generated questions, with stats.
    """
    # Get distinct teachers who have subjects with questions
    query = """
        SELECT 
            u.id,
            u.username,
            u.full_name,
            u.email,
            COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
            array_agg(DISTINCT s.name) FILTER (WHERE s.name IS NOT NULL) as subjects
        FROM users u
        JOIN subjects s ON s.user_id = u.id
        LEFT JOIN questions q ON q.subject_id = s.id
        WHERE u.role = 'teacher'
        GROUP BY u.id, u.username, u.full_name, u.email
        HAVING COUNT(q.id) > 0
        ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
    """
    
    from sqlalchemy import text
    result = await db.execute(text(query))
    rows = result.fetchall()
    
    teachers = []
    for row in rows:
        teachers.append(TeacherSummary(
            id=row[0],
            username=row[1],
            full_name=row[2],
            email=row[3],
            pending_count=row[4] or 0,
            approved_count=row[5] or 0,
            rejected_count=row[6] or 0,
            subjects=row[7] or [],
        ))
    
    return teachers


# ============== Subjects List ==============


@router.get("/subjects", response_model=List[SubjectSummary])
async def get_subjects_with_questions(
    teacher_id: Optional[uuid.UUID] = Query(None, description="Filter by teacher"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of subjects with question stats, optionally filtered by teacher.
    """
    from sqlalchemy import text
    
    base_query = """
        SELECT 
            s.id,
            s.name,
            s.code,
            s.user_id as teacher_id,
            u.full_name as teacher_name,
            COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count
        FROM subjects s
        JOIN users u ON u.id = s.user_id
        LEFT JOIN questions q ON q.subject_id = s.id
    """
    
    if teacher_id:
        base_query += f" WHERE s.user_id = '{teacher_id}'"
    
    base_query += """
        GROUP BY s.id, s.name, s.code, s.user_id, u.full_name
        HAVING COUNT(q.id) > 0
        ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
    """
    
    result = await db.execute(text(base_query))
    rows = result.fetchall()
    
    subjects = []
    for row in rows:
        subject_id = row[0]
        
        # Get topics for this subject
        topics_result = await db.execute(
            select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
        )
        topics = topics_result.scalars().all()
        
        # Get topic stats
        topic_stats = []
        for topic in topics:
            topic_pending = await db.execute(
                select(func.count(Question.id)).where(
                    Question.topic_id == topic.id,
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                )
            )
            topic_stats.append({
                "id": str(topic.id),
                "name": topic.name,
                "pending_count": topic_pending.scalar() or 0,
            })
        
        subjects.append(SubjectSummary(
            id=row[0],
            name=row[1],
            code=row[2],
            teacher_id=row[3],
            teacher_name=row[4] or "Unknown",
            pending_count=row[5] or 0,
            approved_count=row[6] or 0,
            rejected_count=row[7] or 0,
            topics=topic_stats,
        ))
    
    return subjects


# ============== Questions List ==============


@router.get("/questions", response_model=dict)
async def get_questions_for_vetting(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    teacher_id: Optional[uuid.UUID] = Query(None),
    subject_id: Optional[uuid.UUID] = Query(None),
    topic_id: Optional[uuid.UUID] = Query(None),
    question_type: Optional[str] = Query(None),
    status: str = Query("pending", pattern="^(pending|approved|rejected|all)$"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get paginated list of questions for vetting.
    """
    # Build base query
    query = (
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    
    # Apply filters
    if status != "all":
        query = query.where(Question.vetting_status == status)
    
    if subject_id:
        query = query.where(Question.subject_id == subject_id)
    
    if topic_id:
        query = query.where(Question.topic_id == topic_id)
    
    if question_type:
        query = query.where(Question.question_type == question_type)
    
    # Filter by teacher (via subject ownership)
    if teacher_id:
        query = query.where(
            Question.subject_id.in_(
                select(Subject.id).where(Subject.user_id == teacher_id)
            )
        )
    
    # Get total count
    count_query = select(func.count()).select_from(query.subquery())
    total_result = await db.execute(count_query)
    total = total_result.scalar() or 0
    
    # Apply pagination
    offset = (page - 1) * limit
    query = query.order_by(Question.created_at.desc()).offset(offset).limit(limit)
    
    result = await db.execute(query)
    questions = result.scalars().all()
    
    # Build response
    question_responses = []
    for q in questions:
        # Get teacher info from subject
        teacher_name = None
        teacher_id_val = None
        if q.subject:
            # Fetch teacher
            teacher_result = await db.execute(
                select(User).where(User.id == q.subject.user_id)
            )
            teacher = teacher_result.scalar_one_or_none()
            if teacher:
                teacher_name = teacher.full_name or teacher.username
                teacher_id_val = teacher.id
        
        question_responses.append(QuestionForVetting(
            id=q.id,
            question_text=q.question_text,
            question_type=q.question_type,
            options=q.options,
            correct_answer=q.correct_answer,
            explanation=q.explanation,
            expected_answer=q.expected_answer,
            key_points=q.key_points,
            marks=q.marks,
            difficulty_level=q.difficulty_level,
            bloom_taxonomy_level=q.bloom_taxonomy_level,
            vetting_status=q.vetting_status,
            vetting_notes=q.vetting_notes,
            learning_outcome_id=q.learning_outcome_id,
            course_outcome_mapping=q.course_outcome_mapping,
            created_at=q.created_at,
            teacher_id=teacher_id_val,
            teacher_name=teacher_name,
            subject_id=q.subject_id,
            subject_name=q.subject.name if q.subject else None,
            subject_code=q.subject.code if q.subject else None,
            topic_id=q.topic_id,
            topic_name=q.topic.name if q.topic else None,
        ))
    
    return {
        "questions": question_responses,
        "total": total,
        "page": page,
        "limit": limit,
        "pages": (total + limit - 1) // limit,
    }


# ============== Vet Question ==============


@router.post("/questions/{question_id}/vet")
async def vet_question(
    question_id: uuid.UUID,
    vet_data: VetQuestionRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject a question.
    """
    # Get question
    result = await db.execute(
        select(Question).where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()
    
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )
    
    # Update vetting status
    question.vetting_status = vet_data.status
    question.vetting_notes = vet_data.notes
    question.vetted_at = datetime.now(timezone.utc)
    question.vetted_by = current_user.id
    
    # Update CO mapping if provided
    if vet_data.course_outcome_mapping:
        question.course_outcome_mapping = vet_data.course_outcome_mapping
    
    # Store rejection reasons if rejected
    if vet_data.status == "rejected" and vet_data.rejection_reasons:
        question.vetting_notes = f"{vet_data.notes or ''}\nReasons: {', '.join(vet_data.rejection_reasons)}"
        if vet_data.custom_feedback:
            question.vetting_notes += f"\nFeedback: {vet_data.custom_feedback}"
    
    await db.commit()
    
    return {
        "message": f"Question {vet_data.status}",
        "question_id": str(question_id),
        "status": vet_data.status,
    }


# ============== Bulk Vet ==============


@router.post("/questions/bulk-vet")
async def bulk_vet_questions(
    bulk_data: BulkVetRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject multiple questions at once.
    """
    # Get questions
    result = await db.execute(
        select(Question).where(
            Question.id.in_(bulk_data.question_ids),
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    questions = result.scalars().all()
    
    if not questions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No questions found",
        )
    
    # Update all questions
    for question in questions:
        question.vetting_status = bulk_data.status
        question.vetting_notes = bulk_data.notes
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id
    
    await db.commit()
    
    return {
        "message": f"{len(questions)} questions {bulk_data.status}",
        "count": len(questions),
        "status": bulk_data.status,
    }


# ============== Topic Stats ==============


@router.get("/subjects/{subject_id}/topics", response_model=List[TopicQuestionStats])
async def get_topic_stats(
    subject_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get detailed topic stats for a subject.
    """
    # Verify subject exists
    subject_result = await db.execute(
        select(Subject).where(Subject.id == subject_id)
    )
    subject = subject_result.scalar_one_or_none()
    
    if not subject:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Subject not found",
        )
    
    # Get topics with stats
    topics_result = await db.execute(
        select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
    )
    topics = topics_result.scalars().all()
    
    stats = []
    for topic in topics:
        pending = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "pending",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        approved = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "approved",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        rejected = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "rejected",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        
        stats.append(TopicQuestionStats(
            id=topic.id,
            name=topic.name,
            pending_count=pending.scalar() or 0,
            approved_count=approved.scalar() or 0,
            rejected_count=rejected.scalar() or 0,
        ))
    
    return stats
