"""
Vetter Portal API endpoints.

These endpoints are dedicated to vetters who review and approve questions
generated by teachers. Vetters can view questions across all teachers,
filtered by subject and topic.
"""

import uuid
from typing import Optional, List
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy import select, func, and_, or_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload, joinedload
from pydantic import BaseModel, Field

from app.core.database import get_db
from app.core.auth_database import AuthSessionLocal
from app.api.v1.deps import get_current_vetter
from app.models.user import User
from app.models.question import Question
from app.models.subject import Subject, Topic
from app.models.rubric import Rubric
from app.models.training import VettingReasonCode
from app.services.question_service import QuestionGenerationService
from app.services.embedding_service import EmbeddingService
from app.api.v1.deps import get_current_superuser
from app.services.metrics_service import vetting_submit_success_total, vetting_submit_failure_total, edit_distance_mean
from app.schemas.question import QuestionSourceInfo, SourceReference


router = APIRouter()


# ============== Schemas ==============


class TeacherSummary(BaseModel):
    """Summary of a teacher for vetting."""
    id: uuid.UUID
    username: str
    full_name: Optional[str]
    email: str
    pending_count: int
    approved_count: int
    rejected_count: int
    subjects: List[str]
    
    model_config = {"from_attributes": True}


class SubjectSummary(BaseModel):
    """Summary of a subject for vetting."""
    id: uuid.UUID
    name: str
    code: str
    description: Optional[str] = None
    teacher_id: uuid.UUID
    teacher_name: str
    pending_count: int
    approved_count: int
    rejected_count: int
    topics: List[dict]
    
    model_config = {"from_attributes": True}


class TopicQuestionStats(BaseModel):
    """Stats for topics."""
    id: uuid.UUID
    name: str
    pending_count: int
    approved_count: int
    rejected_count: int


class VetterDashboard(BaseModel):
    """Dashboard data for vetters."""
    total_pending: int
    total_approved: int
    total_rejected: int
    teachers_with_pending: int
    subjects_with_pending: int
    recent_submissions: int  # Last 24 hours


class VetterQuestionFilters(BaseModel):
    """Filters for vetter question list."""
    teacher_id: Optional[uuid.UUID] = None
    subject_id: Optional[uuid.UUID] = None
    topic_id: Optional[uuid.UUID] = None
    question_type: Optional[str] = None
    status: Optional[str] = "pending"  # pending, approved, rejected, all
    from_date: Optional[datetime] = None
    to_date: Optional[datetime] = None


class QuestionForVetting(BaseModel):
    """Question data for vetting UI."""
    id: uuid.UUID
    question_text: str
    question_type: str
    options: Optional[List[str]]
    correct_answer: Optional[str]
    explanation: Optional[str]
    marks: Optional[int]
    difficulty_level: Optional[str]
    bloom_taxonomy_level: Optional[str]
    vetting_status: str
    vetting_notes: Optional[str]
    learning_outcome_id: Optional[str]
    course_outcome_mapping: Optional[dict]
    generated_at: datetime
    
    # Teacher info
    teacher_id: Optional[uuid.UUID]
    teacher_name: Optional[str]
    
    # Subject/Topic info
    subject_id: Optional[uuid.UUID]
    subject_name: Optional[str]
    subject_code: Optional[str]
    topic_id: Optional[uuid.UUID]
    topic_name: Optional[str]
    source_info: Optional[QuestionSourceInfo] = None

    # Version control
    version_number: int = 1
    replaces_id: Optional[uuid.UUID] = None
    replaced_by_id: Optional[uuid.UUID] = None

    model_config = {"from_attributes": True}


class VetQuestionRequest(BaseModel):
    """Request to vet a question."""
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None
    course_outcome_mapping: Optional[dict] = None
    rejection_reasons: Optional[List[str]] = None
    custom_feedback: Optional[str] = None


class VetQuestionSubmitRequest(BaseModel):
    """
    Rich vetting submission — supports Edit & Approve, creating DPO pairs.
    Maps to POST /api/vetting/submit.
    """
    question_id: uuid.UUID
    decision: str = Field(..., pattern="^(approve|reject|edit)$")
    # For edits: the corrected question text
    edited_text: Optional[str] = None
    edited_options: Optional[List[str]] = None
    edited_answer: Optional[str] = None
    edited_explanation: Optional[str] = None
    # Rejection details
    rejection_reasons: Optional[List[str]] = None
    reason_codes: Optional[List[str]] = None
    severity_level: Optional[str] = Field(None, pattern="^(minor|major|critical)$")
    quality_score: Optional[float] = Field(None, ge=0.0, le=1.0)
    review_version: int = Field(default=1, ge=1)
    rubric_snapshot: Optional[dict] = None
    field_change_rationale: Optional[dict] = None
    # General feedback
    feedback: Optional[str] = None
    notes: Optional[str] = None
    approved_difficulty: Optional[str] = Field(None, pattern="^(easy|medium|hard)$")
    course_outcome_mapping: Optional[dict] = None
    # Timing (front-end tracks how long the vetter spent)
    time_spent_seconds: Optional[int] = None


class ReasonCodeResponse(BaseModel):
    id: uuid.UUID
    code: str
    label: str
    description: Optional[str]
    severity_default: str
    is_active: bool
    created_at: datetime

    model_config = {"from_attributes": True}


class ReasonCodeCreateRequest(BaseModel):
    code: str = Field(..., min_length=2, max_length=80)
    label: str = Field(..., min_length=2, max_length=255)
    description: Optional[str] = None
    severity_default: str = Field(default="minor", pattern="^(minor|major|critical)$")
    is_active: bool = True


class BulkVetRequest(BaseModel):
    """Request to vet multiple questions at once."""
    question_ids: List[uuid.UUID]
    status: str = Field(..., pattern="^(approved|rejected)$")
    notes: Optional[str] = None


@router.get("/reason-codes", response_model=List[ReasonCodeResponse])
async def list_reason_codes(
    include_inactive: bool = Query(False),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """List controlled reason codes for vetting reject/edit decisions."""
    query = select(VettingReasonCode).order_by(VettingReasonCode.code.asc())
    if not include_inactive:
        query = query.where(VettingReasonCode.is_active == True)

    result = await db.execute(query)
    return result.scalars().all()


@router.post("/reason-codes", response_model=ReasonCodeResponse)
async def create_reason_code(
    payload: ReasonCodeCreateRequest,
    current_user: User = Depends(get_current_superuser),
    db: AsyncSession = Depends(get_db),
):
    """Create a controlled reason-code taxonomy entry. Admin only."""
    existing = await db.execute(select(VettingReasonCode).where(VettingReasonCode.code == payload.code))
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=409, detail="Reason code already exists")

    reason_code = VettingReasonCode(
        code=payload.code,
        label=payload.label,
        description=payload.description,
        severity_default=payload.severity_default,
        is_active=payload.is_active,
        created_by=current_user.id,
    )
    db.add(reason_code)
    await db.commit()
    await db.refresh(reason_code)
    return reason_code


# ============== Dashboard ==============


@router.get("/dashboard", response_model=VetterDashboard)
async def get_vetter_dashboard(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get vetter dashboard with aggregate stats across all teachers.
    """
    # Teachers only see stats for their own subjects
    ownership_filter = []
    if current_user.role == "teacher":
        ownership_filter = [
            Question.subject_id.in_(
                select(Subject.id).where(Subject.user_id == current_user.id)
            )
        ]

    # Count pending questions
    pending_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
            *ownership_filter,
        )
    )
    total_pending = pending_result.scalar() or 0
    
    # Count approved questions
    approved_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "approved",
            Question.is_latest == True,
            Question.is_archived == False,
            *ownership_filter,
        )
    )
    total_approved = approved_result.scalar() or 0
    
    # Count rejected questions
    rejected_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.vetting_status == "rejected",
            Question.is_latest == True,
            Question.is_archived == False,
            *ownership_filter,
        )
    )
    total_rejected = rejected_result.scalar() or 0
    
    # Count teachers with pending questions
    teachers_result = await db.execute(
        select(func.count(func.distinct(Subject.user_id))).where(
            Subject.id.in_(
                select(Question.subject_id).where(
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                    Question.subject_id.isnot(None),
                    *ownership_filter,
                )
            )
        )
    )
    teachers_with_pending = teachers_result.scalar() or 0
    
    # Count subjects with pending questions
    subjects_result = await db.execute(
        select(func.count(func.distinct(Question.subject_id))).where(
            Question.vetting_status == "pending",
            Question.is_latest == True,
            Question.is_archived == False,
            Question.subject_id.isnot(None),
            *ownership_filter,
        )
    )
    subjects_with_pending = subjects_result.scalar() or 0
    
    # Count recent submissions (last 24 hours)
    yesterday = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    recent_result = await db.execute(
        select(func.count(Question.id)).where(
            Question.generated_at >= yesterday,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    recent_submissions = recent_result.scalar() or 0
    
    return VetterDashboard(
        total_pending=total_pending,
        total_approved=total_approved,
        total_rejected=total_rejected,
        teachers_with_pending=teachers_with_pending,
        subjects_with_pending=subjects_with_pending,
        recent_submissions=recent_submissions,
    )


# ============== Teachers List ==============


@router.get("/teachers", response_model=List[TeacherSummary])
async def get_teachers_with_questions(
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of teachers who have generated questions, with stats.
    Users live in SQLite; questions/subjects live in PostgreSQL — joined in Python.
    """
    # 1. Aggregate per-user stats purely from PostgreSQL (no users table)
    from sqlalchemy import text, case as sa_case
    stats_query = text("""
        SELECT
            s.user_id,
            array_agg(DISTINCT s.name) FILTER (WHERE s.name IS NOT NULL) as subject_names,
            COUNT(CASE WHEN q.vetting_status = 'pending'  AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
            COUNT(q.id) as total_questions
        FROM subjects s
        LEFT JOIN questions q ON q.subject_id = s.id
        GROUP BY s.user_id
        HAVING COUNT(q.id) > 0
        ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
    """)
    pg_result = await db.execute(stats_query)
    pg_rows = pg_result.fetchall()

    if not pg_rows:
        return []

    user_ids = [row[0] for row in pg_rows]

    # 2. Fetch matching users from SQLite auth DB
    async with AuthSessionLocal() as auth_session:
        users_result = await auth_session.execute(
            select(User).where(User.id.in_(user_ids), User.role == "teacher")
        )
        users_map = {u.id: u for u in users_result.scalars().all()}

    # 3. Join in Python
    teachers = []
    for row in pg_rows:
        user_id, subject_names, pending, approved, rejected, _ = row
        user = users_map.get(user_id)
        if not user:
            continue
        teachers.append(TeacherSummary(
            id=user.id,
            username=user.username,
            full_name=user.full_name,
            email=user.email,
            pending_count=pending or 0,
            approved_count=approved or 0,
            rejected_count=rejected or 0,
            subjects=subject_names or [],
        ))

    return teachers


# ============== Subjects List ==============


@router.get("/subjects", response_model=List[SubjectSummary])
async def get_subjects_with_questions(
    teacher_id: Optional[uuid.UUID] = Query(None, description="Filter by teacher"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get list of subjects with question stats, optionally filtered by teacher.
    Users live in SQLite; subjects/questions live in PostgreSQL — joined in Python.
    """
    from sqlalchemy import text

    # 1. Aggregate subject stats from PostgreSQL only
    if teacher_id:
        stats_query = text("""
            SELECT
                s.id, s.name, s.code, s.user_id, s.description,
                COUNT(CASE WHEN q.vetting_status = 'pending'  AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
                COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
                COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
                COUNT(q.id) as total_questions
            FROM subjects s
            LEFT JOIN questions q ON q.subject_id = s.id
            WHERE s.user_id = :teacher_id
            GROUP BY s.id, s.name, s.code, s.user_id, s.description
            HAVING COUNT(q.id) > 0
            ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
        """)
        pg_result = await db.execute(stats_query, {"teacher_id": str(teacher_id)})
    else:
        stats_query = text("""
            SELECT
                s.id, s.name, s.code, s.user_id, s.description,
                COUNT(CASE WHEN q.vetting_status = 'pending'  AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
                COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
                COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
                COUNT(q.id) as total_questions
            FROM subjects s
            LEFT JOIN questions q ON q.subject_id = s.id
            GROUP BY s.id, s.name, s.code, s.user_id, s.description
            HAVING COUNT(q.id) > 0
            ORDER BY COUNT(CASE WHEN q.vetting_status = 'pending' AND q.is_latest = true THEN 1 END) DESC
        """)
        pg_result = await db.execute(stats_query)

    pg_rows = pg_result.fetchall()

    if not pg_rows:
        return []

    # 2. Fetch teacher names from SQLite for the distinct user_ids
    user_ids = list({row[3] for row in pg_rows})
    async with AuthSessionLocal() as auth_session:
        users_result = await auth_session.execute(
            select(User).where(User.id.in_(user_ids))
        )
        users_map = {u.id: u for u in users_result.scalars().all()}

    # 3. Build response, fetching topic stats per subject
    subjects = []
    for row in pg_rows:
        subject_id, name, code, user_id, description, pending_count, approved_count, rejected_count, _ = row
        teacher = users_map.get(user_id)
        teacher_name = (teacher.full_name or teacher.username) if teacher else "Unknown"

        # Get topics for this subject
        topics_result = await db.execute(
            select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
        )
        topics = topics_result.scalars().all()

        topic_stats = []
        for topic in topics:
            topic_pending = await db.execute(
                select(func.count(Question.id)).where(
                    Question.topic_id == topic.id,
                    Question.vetting_status == "pending",
                    Question.is_latest == True,
                    Question.is_archived == False,
                )
            )
            topic_stats.append({
                "id": str(topic.id),
                "name": topic.name,
                "pending_count": topic_pending.scalar() or 0,
            })

        subjects.append(SubjectSummary(
            id=subject_id,
            name=name,
            code=code,
            description=description,
            teacher_id=user_id,
            teacher_name=teacher_name,
            pending_count=pending_count or 0,
            approved_count=approved_count or 0,
            rejected_count=rejected_count or 0,
            topics=topic_stats,
        ))

    return subjects


@router.get("/subjects/{subject_id}", response_model=SubjectSummary)
async def get_subject_for_vetting(
    subject_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """Get a single subject summary for vetters."""
    from sqlalchemy import text

    stats_query = text("""
        SELECT
            s.id, s.name, s.code, s.user_id, s.description,
            COUNT(CASE WHEN q.vetting_status = 'pending'  AND q.is_latest = true AND q.is_archived = false THEN 1 END) as pending_count,
            COUNT(CASE WHEN q.vetting_status = 'approved' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as approved_count,
            COUNT(CASE WHEN q.vetting_status = 'rejected' AND q.is_latest = true AND q.is_archived = false THEN 1 END) as rejected_count,
            COUNT(q.id) as total_questions
        FROM subjects s
        LEFT JOIN questions q ON q.subject_id = s.id
        WHERE s.id = :subject_id
        GROUP BY s.id, s.name, s.code, s.user_id, s.description
    """)
    pg_result = await db.execute(stats_query, {"subject_id": str(subject_id)})
    row = pg_result.fetchone()

    if not row:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Subject not found")

    sid, name, code, user_id, description, pending_count, approved_count, rejected_count, _ = row

    async with AuthSessionLocal() as auth_session:
        user_result = await auth_session.execute(select(User).where(User.id == user_id))
        teacher = user_result.scalar_one_or_none()
    teacher_name = (teacher.full_name or teacher.username) if teacher else "Unknown"

    topics_result = await db.execute(
        select(Topic).where(Topic.subject_id == sid).order_by(Topic.order_index)
    )
    topics = topics_result.scalars().all()
    topic_stats = []
    for topic in topics:
        topic_pending = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "pending",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        topic_stats.append({
            "id": str(topic.id),
            "name": topic.name,
            "pending_count": topic_pending.scalar() or 0,
        })

    return SubjectSummary(
        id=sid,
        name=name,
        code=code,
        description=description,
        teacher_id=user_id,
        teacher_name=teacher_name,
        pending_count=pending_count or 0,
        approved_count=approved_count or 0,
        rejected_count=rejected_count or 0,
        topics=topic_stats,
    )


@router.get("/questions", response_model=dict)
async def get_questions_for_vetting(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    teacher_id: Optional[uuid.UUID] = Query(None),
    subject_id: Optional[uuid.UUID] = Query(None),
    topic_id: Optional[uuid.UUID] = Query(None),
    question_type: Optional[str] = Query(None),
    status: str = Query("pending", pattern="^(pending|approved|rejected|all)$"),
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get paginated list of questions for vetting.
    """
    # Build base query
    query = (
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    
    # Apply filters
    if status != "all":
        query = query.where(Question.vetting_status == status)
    
    if subject_id:
        query = query.where(Question.subject_id == subject_id)
    
    if topic_id:
        query = query.where(Question.topic_id == topic_id)
    
    if question_type:
        query = query.where(Question.question_type == question_type)
    
    # Filter by teacher (via subject ownership)
    if teacher_id:
        query = query.where(
            Question.subject_id.in_(
                select(Subject.id).where(Subject.user_id == teacher_id)
            )
        )
    
    # Teachers automatically scoped to their own subjects
    if current_user.role == "teacher" and not teacher_id:
        query = query.where(
            Question.subject_id.in_(
                select(Subject.id).where(Subject.user_id == current_user.id)
            )
        )
    
    # Get total count
    count_query = select(func.count()).select_from(query.subquery())
    total_result = await db.execute(count_query)
    total = total_result.scalar() or 0
    
    # Apply pagination
    offset = (page - 1) * limit
    query = query.order_by(Question.generated_at.desc()).offset(offset).limit(limit)
    
    result = await db.execute(query)
    questions = result.scalars().all()
    
    # Build response
    question_responses = []
    for q in questions:
        # Get teacher info from subject
        teacher_name = None
        teacher_id_val = None
        if q.subject:
            # Fetch teacher from auth DB (cross-database lookup)
            async with AuthSessionLocal() as auth_session:
                teacher_result = await auth_session.execute(
                    select(User).where(User.id == q.subject.user_id)
                )
                teacher = teacher_result.scalar_one_or_none()
            if teacher:
                teacher_name = teacher.full_name or teacher.username
                teacher_id_val = teacher.id
        
        # Extract source_info from generation_metadata
        source_info = None
        if q.generation_metadata:
            metadata = q.generation_metadata
            if "source_info" in metadata:
                source_info = QuestionSourceInfo(**metadata["source_info"])
            elif "sources" in metadata:
                source_info = QuestionSourceInfo(
                    sources=[SourceReference(**s) for s in metadata.get("sources", [])],
                    generation_reasoning=metadata.get("generation_reasoning"),
                    content_coverage=metadata.get("content_coverage"),
                )

        question_responses.append(QuestionForVetting(
            id=q.id,
            question_text=q.question_text,
            question_type=q.question_type,
            options=q.options,
            correct_answer=q.correct_answer,
            explanation=q.explanation,
            marks=q.marks,
            difficulty_level=q.difficulty_level,
            bloom_taxonomy_level=q.bloom_taxonomy_level,
            vetting_status=q.vetting_status,
            vetting_notes=q.vetting_notes,
            learning_outcome_id=q.learning_outcome_id,
            course_outcome_mapping=q.course_outcome_mapping,
            generated_at=q.generated_at,
            teacher_id=teacher_id_val,
            teacher_name=teacher_name,
            subject_id=q.subject_id,
            subject_name=q.subject.name if q.subject else None,
            subject_code=q.subject.code if q.subject else None,
            topic_id=q.topic_id,
            topic_name=q.topic.name if q.topic else None,
            source_info=source_info,
            version_number=q.version_number or 1,
            replaces_id=q.replaces_id,
            replaced_by_id=q.replaced_by_id,
        ))
    
    return {
        "questions": question_responses,
        "total": total,
        "page": page,
        "limit": limit,
        "pages": (total + limit - 1) // limit,
    }


# ============== Vet Question ==============


@router.post("/questions/{question_id}/vet")
async def vet_question(
    question_id: uuid.UUID,
    vet_data: VetQuestionRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject a question.
    """
    # Get question
    result = await db.execute(
        select(Question).where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()
    
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )
    
    # Update vetting status
    question.vetting_status = vet_data.status
    question.vetting_notes = vet_data.notes
    question.vetted_at = datetime.now(timezone.utc)
    question.vetted_by = current_user.id
    
    # Update CO mapping if provided
    if vet_data.course_outcome_mapping:
        question.course_outcome_mapping = vet_data.course_outcome_mapping
    
    # Store rejection reasons if rejected
    if vet_data.status == "rejected" and vet_data.rejection_reasons:
        question.vetting_notes = f"{vet_data.notes or ''}\nReasons: {', '.join(vet_data.rejection_reasons)}"
        if vet_data.custom_feedback:
            question.vetting_notes += f"\nFeedback: {vet_data.custom_feedback}"
    
    await db.commit()
    
    return {
        "message": f"Question {vet_data.status}",
        "question_id": str(question_id),
        "status": vet_data.status,
    }


# ============== Rich Vetting Submit (DPO Pair Creation) ==============


@router.post("/submit")
async def submit_vetting(
    data: VetQuestionSubmitRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Rich vetting endpoint that captures edit diffs and creates DPO training pairs.

    - **approve**: Marks question as approved. Stored as positive SFT sample.
    - **reject**: Marks as rejected. Stores rejection reasons + embedding for RAG.
    - **edit**: Saves (original, edited) pair for DPO training, then approves.
    """
    import hashlib
    from difflib import SequenceMatcher
    from app.models.training import VettingLog, TrainingPair
    try:
        # 1. Load the question
        result = await db.execute(
            select(Question)
            .options(selectinload(Question.topic), selectinload(Question.subject))
            .where(
                Question.id == data.question_id,
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        question = result.scalar_one_or_none()
        if not question:
            raise HTTPException(status_code=404, detail="Question not found")

        if data.approved_difficulty and data.decision != "approve":
            raise HTTPException(
                status_code=400,
                detail="approved_difficulty can only be sent with approve decisions",
            )
        if data.decision == "reject" and (not data.reason_codes or len(data.reason_codes) == 0):
            raise HTTPException(
                status_code=422,
                detail="At least one structured reason code is required when rejecting",
            )

        # Validate reason codes against controlled taxonomy
        if data.reason_codes:
            valid_codes_result = await db.execute(
                select(VettingReasonCode.code).where(
                    VettingReasonCode.code.in_(data.reason_codes),
                    VettingReasonCode.is_active == True,
                )
            )
            valid_codes = {row[0] for row in valid_codes_result.fetchall()}
            invalid_codes = sorted(set(data.reason_codes) - valid_codes)
            if invalid_codes:
                raise HTTPException(
                    status_code=422,
                    detail=f"Invalid reason codes: {', '.join(invalid_codes)}",
                )

        rubric_snapshot = data.rubric_snapshot
        if rubric_snapshot is None and question.subject_id:
            latest_rubric_result = await db.execute(
                select(Rubric)
                .where(Rubric.subject_id == question.subject_id)
                .order_by(Rubric.updated_at.desc())
                .limit(1)
            )
            latest_rubric = latest_rubric_result.scalar_one_or_none()
            if latest_rubric:
                rubric_snapshot = {
                    "rubric_id": str(latest_rubric.id),
                    "name": latest_rubric.name,
                    "exam_type": latest_rubric.exam_type,
                    "question_type_distribution": latest_rubric.question_type_distribution,
                    "learning_outcomes_distribution": latest_rubric.learning_outcomes_distribution,
                }

        # 2. Build the edit diff (for 'edit' decisions)
        edit_diff = None
        original_text = question.question_text
        if data.decision == "edit":
            edit_diff = {}
            rationale = data.field_change_rationale or {}
            if data.edited_text and data.edited_text != question.question_text:
                edit_diff["question_text"] = {
                    "old": question.question_text,
                    "new": data.edited_text,
                    "rationale": rationale.get("question_text"),
                }
            if data.edited_options is not None and data.edited_options != question.options:
                edit_diff["options"] = {
                    "old": question.options,
                    "new": data.edited_options,
                    "rationale": rationale.get("options"),
                }
            if data.edited_answer and data.edited_answer != question.correct_answer:
                edit_diff["correct_answer"] = {
                    "old": question.correct_answer,
                    "new": data.edited_answer,
                    "rationale": rationale.get("correct_answer"),
                }
            if data.edited_explanation and data.edited_explanation != question.explanation:
                edit_diff["explanation"] = {
                    "old": question.explanation,
                    "new": data.edited_explanation,
                    "rationale": rationale.get("explanation"),
                }

        # 3. Create VettingLog
        vetting_log = VettingLog(
            question_id=data.question_id,
            vetter_id=current_user.id,
            decision=data.decision,
            review_version=data.review_version,
            quality_score=data.quality_score,
            rubric_snapshot=rubric_snapshot,
            reason_codes=data.reason_codes,
            severity_level=data.severity_level,
            original_text=original_text,
            edited_text=data.edited_text if data.decision == "edit" else None,
            edit_diff=edit_diff,
            rejection_reasons=data.rejection_reasons if data.decision == "reject" else None,
            feedback=data.feedback or data.notes,
            approved_difficulty=data.approved_difficulty if data.decision == "approve" else None,
            time_spent_seconds=data.time_spent_seconds,
        )

        # Embed rejection reasons for RAG retrieval
        if data.decision == "reject" and data.rejection_reasons:
            try:
                embedding_service = EmbeddingService()
                reason_text = "; ".join(data.rejection_reasons)
                embedding = await embedding_service.get_embedding(reason_text)
                vetting_log.rejection_reason_embedding = embedding
            except Exception:
                pass  # Non-critical — skip if embedding service unavailable

        db.add(vetting_log)
        await db.flush()

        # 4. Update the question itself
        if data.decision == "approve":
            question.vetting_status = "approved"
            if data.approved_difficulty:
                question.difficulty_level = data.approved_difficulty
        elif data.decision == "reject":
            question.vetting_status = "rejected"
        elif data.decision == "edit":
            # Apply edits and approve
            if data.edited_text:
                question.question_text = data.edited_text
            if data.edited_options is not None:
                question.options = data.edited_options
            if data.edited_answer:
                question.correct_answer = data.edited_answer
            if data.edited_explanation:
                question.explanation = data.edited_explanation
            question.vetting_status = "approved"

        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id
        question.vetting_notes = data.notes or data.feedback

        if data.course_outcome_mapping:
            question.course_outcome_mapping = data.course_outcome_mapping

        # 5. Create DPO training pair when appropriate
        training_pair = None
        if data.decision == "edit" and edit_diff:
            generation_prompt = _reconstruct_prompt(question)
            chosen_text = data.edited_text or original_text
            dedupe_source = f"{generation_prompt}|{chosen_text}|{original_text}|edit"
            training_pair = TrainingPair(
                prompt=generation_prompt,
                chosen_response=chosen_text,
                rejected_response=original_text,
                vetting_log_id=vetting_log.id,
                chosen_question_id=question.id,
                rejected_question_id=question.id,
                pair_type="edit",
                confidence=0.9,
                pair_weight=1.0,
                language="en",
                source_split="train",
                dedupe_hash=hashlib.sha256(dedupe_source.encode("utf-8")).hexdigest(),
                rejected_reason_codes=data.reason_codes,
            )
            db.add(training_pair)

            if chosen_text and original_text:
                ratio = 1.0 - SequenceMatcher(None, original_text, chosen_text).ratio()
                edit_distance_mean.set(ratio)

        elif data.decision == "reject" and data.reason_codes:
            generation_prompt = _reconstruct_prompt(question)
            dedupe_source = f"{generation_prompt}|{original_text}|reject"
            training_pair = TrainingPair(
                prompt=generation_prompt,
                chosen_response="",
                rejected_response=original_text,
                vetting_log_id=vetting_log.id,
                rejected_question_id=question.id,
                pair_type="reject_approve",
                status="pending",
                confidence=0.7,
                pair_weight=0.8,
                language="en",
                source_split="train",
                dedupe_hash=hashlib.sha256(dedupe_source.encode("utf-8")).hexdigest(),
                rejected_reason_codes=data.reason_codes,
            )
            db.add(training_pair)

        await db.commit()
        vetting_submit_success_total.inc()

        action_label = {
            "approve": "approved",
            "reject": "rejected",
            "edit": "updated",
        }[data.decision]

        return {
            "message": f"Question {action_label} successfully",
            "question_id": str(data.question_id),
            "decision": data.decision,
            "vetting_log_id": str(vetting_log.id),
            "training_pair_created": training_pair is not None,
        }
    except HTTPException:
        vetting_submit_failure_total.inc()
        raise
    except Exception:
        vetting_submit_failure_total.inc()
        raise


def _reconstruct_prompt(question: Question) -> str:
    """
    Reconstruct the generation prompt from question metadata.
    Used as the 'prompt' field in DPO training pairs.
    """
    parts = []
    if question.generation_metadata:
        meta = question.generation_metadata
        if "system_prompt" in meta:
            parts.append(meta["system_prompt"])
        if "user_prompt" in meta:
            parts.append(meta["user_prompt"])
    if not parts:
        # Fallback: construct from question attributes
        parts.append(f"Generate a {question.question_type or 'question'}")
        if question.difficulty_level:
            parts.append(f"at {question.difficulty_level} difficulty")
        loaded_topic = question.__dict__.get("topic")
        if loaded_topic and getattr(loaded_topic, "name", None):
            parts.append(f"about {loaded_topic.name}")
        elif question.topic_tags:
            parts.append(f"about {question.topic_tags[0]}")
    return "\n".join(parts)


# ============== Bulk Vet ==============


@router.post("/questions/bulk-vet")
async def bulk_vet_questions(
    bulk_data: BulkVetRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Approve or reject multiple questions at once.
    """
    # Get questions
    result = await db.execute(
        select(Question).where(
            Question.id.in_(bulk_data.question_ids),
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    questions = result.scalars().all()
    
    if not questions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No questions found",
        )
    
    # Update all questions
    for question in questions:
        question.vetting_status = bulk_data.status
        question.vetting_notes = bulk_data.notes
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id
    
    await db.commit()
    
    return {
        "message": f"{len(questions)} questions {bulk_data.status}",
        "count": len(questions),
        "status": bulk_data.status,
    }


# ============== Topic Stats ==============


@router.get("/subjects/{subject_id}/topics", response_model=List[TopicQuestionStats])
async def get_topic_stats(
    subject_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get detailed topic stats for a subject.
    """
    # Verify subject exists
    subject_result = await db.execute(
        select(Subject).where(Subject.id == subject_id)
    )
    subject = subject_result.scalar_one_or_none()
    
    if not subject:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Subject not found",
        )
    
    # Get topics with stats
    topics_result = await db.execute(
        select(Topic).where(Topic.subject_id == subject_id).order_by(Topic.order_index)
    )
    topics = topics_result.scalars().all()
    
    stats = []
    for topic in topics:
        pending = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "pending",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        approved = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "approved",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        rejected = await db.execute(
            select(func.count(Question.id)).where(
                Question.topic_id == topic.id,
                Question.vetting_status == "rejected",
                Question.is_latest == True,
                Question.is_archived == False,
            )
        )
        
        stats.append(TopicQuestionStats(
            id=topic.id,
            name=topic.name,
            pending_count=pending.scalar() or 0,
            approved_count=approved.scalar() or 0,
            rejected_count=rejected.scalar() or 0,
        ))
    
    return stats


# ============== Update Question (Vetter) ==============


class RejectAndRegenerateRequest(BaseModel):
    """Request to reject a question and trigger regeneration."""
    notes: Optional[str] = None
    rejection_reasons: Optional[List[str]] = None
    custom_feedback: Optional[str] = None


class RejectWithFeedbackRequest(BaseModel):
    """Request to reject a question with feedback for improvement or replacement."""
    feedback: str = Field(..., min_length=1, max_length=2000)
    rejection_reasons: Optional[List[str]] = None
    generate_new: bool = False  # If True: generate brand new question. If False: improve the rejected one.


@router.post("/questions/{question_id}/reject-with-feedback")
async def reject_with_feedback(
    question_id: uuid.UUID,
    req: RejectWithFeedbackRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Reject a question with feedback. Either improves the current question or generates a new one.
    - Default (generate_new=false): Uses LLM to improve the same question based on feedback.
    - generate_new=true: Generates a completely new replacement question.
    Both create DPO training pairs for the training pipeline.
    """
    import logging
    logger = logging.getLogger(__name__)
    from app.models.training import VettingLog, TrainingPair

    # 1. Load question
    result = await db.execute(
        select(Question)
        .options(selectinload(Question.subject), selectinload(Question.topic))
        .where(Question.id == question_id, Question.is_latest == True, Question.is_archived == False)
    )
    question = result.scalar_one_or_none()
    if not question:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")

    original_text = question.question_text
    original_options = question.options
    original_answer = question.correct_answer
    original_explanation = question.explanation

    # 2. Create VettingLog
    vetting_log = VettingLog(
        question_id=question.id,
        vetter_id=str(current_user.id),
        decision="reject",
        original_text=original_text,
        rejection_reasons=req.rejection_reasons or [req.feedback[:200]],
        feedback=req.feedback,
    )
    db.add(vetting_log)

    # 3. If generate_new, delegate to existing regeneration logic
    if req.generate_new:
        await db.flush()
        # Mark rejected
        question.vetting_status = "rejected"
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id
        question.is_latest = False

        # Create DPO pair (rejected signal — chosen will be filled when replacement is approved)
        generation_prompt = _reconstruct_prompt(question)
        training_pair = TrainingPair(
            prompt=generation_prompt,
            chosen_response="",
            rejected_response=original_text,
            vetting_log_id=vetting_log.id,
            rejected_question_id=question.id,
            pair_type="reject_approve",
            status="pending",
            confidence=0.7,
        )
        db.add(training_pair)

        # Regenerate using existing logic
        from app.models.document import Document, DocumentChunk
        from app.models.question import GenerationSession
        import random, numpy as np

        teacher_id = question.subject.user_id if question.subject else None
        document_id = question.document_id

        if not document_id and question.subject_id:
            doc_result = await db.execute(
                select(Document.id).where(
                    Document.subject_id == question.subject_id,
                    Document.processing_status == "completed",
                ).order_by(Document.upload_timestamp.desc()).limit(1)
            )
            document_id = doc_result.scalar_one_or_none()

        if document_id and teacher_id:
            chunks_result = await db.execute(
                select(DocumentChunk)
                .options(joinedload(DocumentChunk.document))
                .where(DocumentChunk.document_id == document_id)
                .order_by(DocumentChunk.chunk_index)
            )
            chunks = list(chunks_result.scalars().all())

            if chunks:
                gen_service = QuestionGenerationService(db)
                embedding_service = EmbeddingService()
                new_q_data = None

                # Load existing embeddings for dedupe
                existing_embeddings = []
                if question.subject_id:
                    try:
                        emb_res = await db.execute(
                            select(Question.question_embedding).where(
                                Question.subject_id == question.subject_id,
                                Question.is_archived == False,
                                Question.question_embedding.isnot(None),
                            ).limit(2000)
                        )
                        existing_embeddings = [r[0] for r in emb_res.all()]
                    except Exception:
                        pass

                for attempt in range(3):
                    try:
                        selected = random.sample(chunks, min(3, len(chunks)))
                        candidate = await gen_service._generate_single_question(
                            chunks=selected,
                            question_type=question.question_type,
                            difficulty=question.difficulty_level or "medium",
                            marks=question.marks,
                            bloom_levels=[question.bloom_taxonomy_level] if question.bloom_taxonomy_level else None,
                        )
                        if not candidate:
                            continue

                        if existing_embeddings:
                            emb = await embedding_service.get_embedding(candidate["question_text"])
                            q_vec = np.array(emb)
                            matrix = np.array(existing_embeddings)
                            q_norm = q_vec / (np.linalg.norm(q_vec) or 1.0)
                            norms = np.linalg.norm(matrix, axis=1, keepdims=True)
                            norms[norms == 0] = 1.0
                            if float(np.max(np.dot(matrix / norms, q_norm))) > 0.85:
                                continue

                        new_q_data = candidate
                        break
                    except Exception as e:
                        logger.error(f"reject-with-feedback regen attempt {attempt+1}: {e}")

                if new_q_data:
                    session_id = question.session_id
                    if not session_id:
                        s = GenerationSession(
                            user_id=teacher_id, document_id=document_id,
                            subject_id=question.subject_id, topic_id=question.topic_id,
                            generation_method="vetter_regen", requested_count=1,
                            status="completed", started_at=datetime.now(timezone.utc),
                            completed_at=datetime.now(timezone.utc), questions_generated=1,
                        )
                        db.add(s)
                        await db.flush()
                        session_id = s.id

                    new_question, _ = await gen_service._save_question(
                        document_id=document_id, session_id=session_id,
                        question_data=new_q_data, question_type=question.question_type,
                        marks=question.marks, difficulty=question.difficulty_level or "medium",
                        chunk_ids=[c.id for c in selected], chunks=selected,
                        subject_id=question.subject_id, topic_id=question.topic_id,
                    )
                    new_question.replaces_id = question_id
                    new_question.version_number = (question.version_number or 1) + 1
                    new_question.is_latest = True
                    new_question.vetting_status = "pending"
                    question.replaced_by_id = new_question.id

                    new_source_info = None
                    gen_meta = new_question.generation_metadata or {}
                    if "source_info" in gen_meta:
                        meta_si = gen_meta["source_info"]
                        if meta_si:
                            new_source_info = QuestionSourceInfo(**meta_si).model_dump()
                    elif "sources" in gen_meta:
                        new_source_info = QuestionSourceInfo(
                            sources=[SourceReference(**s) for s in gen_meta.get("sources", [])],
                            generation_reasoning=gen_meta.get("generation_reasoning"),
                            content_coverage=gen_meta.get("content_coverage"),
                        ).model_dump()

                    await db.commit()
                    return {
                        "message": "Question rejected and new replacement generated",
                        "question_id": str(question_id),
                        "new_question_id": str(new_question.id),
                        "new_question": {
                            "id": str(new_question.id),
                            "question_text": new_question.question_text,
                            "question_type": new_question.question_type,
                            "options": new_question.options,
                            "correct_answer": new_question.correct_answer,
                            "explanation": new_question.explanation,
                            "marks": new_question.marks,
                            "difficulty_level": new_question.difficulty_level,
                            "bloom_taxonomy_level": new_question.bloom_taxonomy_level,
                            "vetting_status": new_question.vetting_status,
                            "vetting_notes": new_question.vetting_notes,
                            "generated_at": new_question.generated_at.isoformat(),
                            "teacher_id": str(teacher_id) if teacher_id else None,
                            "teacher_name": None,
                            "subject_id": str(new_question.subject_id) if new_question.subject_id else None,
                            "subject_name": question.subject.name if question.subject else None,
                            "subject_code": question.subject.code if question.subject else None,
                            "topic_id": str(new_question.topic_id) if new_question.topic_id else None,
                            "topic_name": question.topic.name if question.topic else None,
                            "source_info": new_source_info,
                            "version_number": new_question.version_number or 1,
                            "replaces_id": str(new_question.replaces_id) if new_question.replaces_id else None,
                            "replaced_by_id": str(new_question.replaced_by_id) if new_question.replaced_by_id else None,
                        },
                        "decision": "reject",
                        "regenerated": True,
                        "improved": False,
                    }

        # Regen failed — just reject
        question.is_latest = True
        await db.commit()
        return {
            "message": "Question rejected (regeneration failed)",
            "question_id": str(question_id),
            "decision": "reject",
            "regenerated": False,
            "improved": False,
        }

    # 4. IMPROVE mode (default) — use LLM to improve the same question based on feedback
    from app.services.llm_service import LLMService
    llm = LLMService()

    improve_prompt = f"""You are a question quality improvement assistant. A reviewer rejected a question and provided feedback. 
Your task is to IMPROVE the same question based on the feedback. Do NOT create a completely different question.
Keep the same topic, type, and difficulty level. Only fix what the reviewer flagged.

REJECTED QUESTION:
Type: {question.question_type}
Text: {original_text}
"""
    if original_options:
        improve_prompt += f"Options: {', '.join(original_options)}\n"
    if original_answer:
        improve_prompt += f"Correct Answer: {original_answer}\n"
    if original_explanation:
        improve_prompt += f"Explanation: {original_explanation}\n"

    improve_prompt += f"""
REVIEWER FEEDBACK:
{req.feedback}
"""
    if req.rejection_reasons:
        improve_prompt += f"Rejection Reasons: {', '.join(req.rejection_reasons)}\n"

    improve_prompt += """
INSTRUCTIONS:
- Improve the question based on the feedback
- Keep the same topic and difficulty
- Fix ONLY the issues mentioned in the feedback
- Return ONLY valid JSON with these fields:
{
  "question_text": "improved question text",
  "options": ["A) ...", "B) ...", "C) ...", "D) ..."],
  "correct_answer": "letter of correct option",
  "explanation": "explanation of the answer"
}
For non-MCQ questions, omit the "options" field.
Return ONLY the JSON, no other text."""

    try:
        import json as json_module
        llm_response = await llm.generate(improve_prompt, temperature=0.3)
        # Parse the JSON response
        cleaned = llm_response.strip()
        # Extract JSON from potential markdown code blocks
        if "```json" in cleaned:
            cleaned = cleaned.split("```json")[1].split("```")[0].strip()
        elif "```" in cleaned:
            cleaned = cleaned.split("```")[1].split("```")[0].strip()

        improved = json_module.loads(cleaned)

        improved_text = improved.get("question_text", original_text)
        improved_options = improved.get("options", original_options)
        improved_answer = improved.get("correct_answer", original_answer)
        improved_explanation = improved.get("explanation", original_explanation)

        # Build edit diff
        edit_diff = {}
        if improved_text != original_text:
            edit_diff["question_text"] = {"old": original_text, "new": improved_text}
        if improved_options != original_options:
            edit_diff["options"] = {"old": original_options, "new": improved_options}
        if improved_answer != original_answer:
            edit_diff["correct_answer"] = {"old": original_answer, "new": improved_answer}
        if improved_explanation != original_explanation:
            edit_diff["explanation"] = {"old": original_explanation, "new": improved_explanation}

        # Update the vetting log with edit info
        vetting_log.edited_text = improved_text
        vetting_log.edit_diff = edit_diff

        # Apply improvements to the question
        question.question_text = improved_text
        if improved_options:
            question.options = improved_options
        question.correct_answer = improved_answer
        question.explanation = improved_explanation
        question.vetting_status = "pending"  # Back to pending for re-review
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id

        # Create DPO training pair (original=rejected, improved=chosen)
        generation_prompt = _reconstruct_prompt(question)
        training_pair = TrainingPair(
            prompt=generation_prompt,
            chosen_response=improved_text,
            rejected_response=original_text,
            vetting_log_id=vetting_log.id,
            chosen_question_id=question.id,
            rejected_question_id=question.id,
            pair_type="edit",
            confidence=0.8,  # Slightly lower than manual edit since LLM-mediated
        )
        db.add(training_pair)

        await db.commit()
        return {
            "message": "Question improved based on feedback",
            "question_id": str(question_id),
            "decision": "reject",
            "improved": True,
            "regenerated": False,
            "improved_text": improved_text,
            "improved_options": improved_options,
            "improved_answer": improved_answer,
            "improved_explanation": improved_explanation,
            "changes": edit_diff,
        }

    except Exception as e:
        logger.error(f"reject-with-feedback improve failed: {e}")
        # Fallback: just reject without improvement
        question.vetting_status = "rejected"
        question.vetted_at = datetime.now(timezone.utc)
        question.vetted_by = current_user.id

        generation_prompt = _reconstruct_prompt(question)
        training_pair = TrainingPair(
            prompt=generation_prompt,
            chosen_response="",
            rejected_response=original_text,
            vetting_log_id=vetting_log.id,
            rejected_question_id=question.id,
            pair_type="reject_approve",
            status="pending",
            confidence=0.7,
        )
        db.add(training_pair)
        await db.commit()

        return {
            "message": "Question rejected (improvement failed, saved as training signal)",
            "question_id": str(question_id),
            "decision": "reject",
            "improved": False,
            "regenerated": False,
            "error": str(e),
        }


# ============== Reject and Regenerate ==============


@router.post("/questions/{question_id}/reject-and-regenerate")
async def reject_and_regenerate_question(
    question_id: uuid.UUID,
    vet_data: RejectAndRegenerateRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Reject a question and automatically regenerate a replacement.
    Creates a new GenerationSession (vetter_regen) linked to the teacher's account,
    so it appears in their history. The new question replaces the rejected one.
    """
    import logging
    import random
    from app.models.question import GenerationSession
    from app.models.document import DocumentChunk

    logger = logging.getLogger(__name__)

    # 1. Get the question with subject loaded
    result = await db.execute(
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()

    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )

    # 2. Build rejection notes
    rejection_notes = vet_data.notes or ""
    if vet_data.rejection_reasons:
        rejection_notes = f"{rejection_notes}\nReasons: {', '.join(vet_data.rejection_reasons)}".strip()
    if vet_data.custom_feedback:
        rejection_notes = f"{rejection_notes}\nFeedback: {vet_data.custom_feedback}".strip()

    # 3. Mark original as rejected and NOT latest
    question.vetting_status = "rejected"
    question.vetting_notes = rejection_notes or None
    question.vetted_at = datetime.now(timezone.utc)
    question.vetted_by = current_user.id
    question.is_latest = False

    # Get teacher's user_id from subject
    teacher_id = question.subject.user_id if question.subject else None
    document_id = question.document_id

    # 4. If document_id is null but subject_id exists, find any usable document for the subject
    if not document_id and question.subject_id:
        from app.models.document import Document
        doc_result = await db.execute(
            select(Document.id)
            .where(
                Document.subject_id == question.subject_id,
                Document.processing_status == "completed",
            )
            .order_by(Document.upload_timestamp.desc())
            .limit(1)
        )
        fallback_doc_id = doc_result.scalar_one_or_none()
        if fallback_doc_id:
            document_id = fallback_doc_id

    # 5. If still no document or no teacher, just reject (restore is_latest=True)
    if not document_id or not teacher_id:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (no document available for regeneration)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 5. Get document chunks (join document so _build_source_info can read filename)
    chunks_result = await db.execute(
        select(DocumentChunk)
        .options(joinedload(DocumentChunk.document))
        .where(DocumentChunk.document_id == document_id)
        .order_by(DocumentChunk.chunk_index)
    )
    chunks = chunks_result.scalars().all()

    if not chunks:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (no document content available for regeneration)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 6. Preload existing embeddings for subject-level dedupe
    existing_embeddings = []
    if question.subject_id:
        try:
            emb_res = await db.execute(
                select(Question.question_embedding).where(
                    Question.subject_id == question.subject_id,
                    Question.is_archived == False,
                    Question.question_embedding.isnot(None),
                ).limit(2000)
            )
            existing_embeddings = [r[0] for r in emb_res.all()]
            logger.info(f"reject_and_regenerate: Preloaded {len(existing_embeddings)} existing embeddings for dedupe")
        except Exception as e:
            logger.warning(f"reject_and_regenerate: Could not preload existing embeddings: {e}")

    # 7. Generate a replacement question (with dedupe retry loop)
    import numpy as np
    gen_service = QuestionGenerationService(db)
    embedding_service = EmbeddingService()
    question_data = None
    selected_chunks = chunks[:3]  # fallback; overwritten on each attempt
    REGEN_MAX_ATTEMPTS = 3
    for attempt in range(REGEN_MAX_ATTEMPTS):
        try:
            selected_chunks = random.sample(chunks, min(3, len(chunks)))
            candidate_data = await gen_service._generate_single_question(
                chunks=selected_chunks,
                question_type=question.question_type,
                difficulty=question.difficulty_level or "medium",
                marks=question.marks,
                bloom_levels=[question.bloom_taxonomy_level] if question.bloom_taxonomy_level else None,
            )
            if not candidate_data:
                continue

            # Embedding-based dedupe check
            if existing_embeddings:
                candidate_emb = await embedding_service.get_embedding(candidate_data["question_text"])
                q_vec = np.array(candidate_emb)
                matrix = np.array(existing_embeddings)
                q_norm = q_vec / (np.linalg.norm(q_vec) or 1.0)
                norms = np.linalg.norm(matrix, axis=1, keepdims=True)
                norms[norms == 0] = 1.0
                max_sim = float(np.max(np.dot(matrix / norms, q_norm)))
                if max_sim > 0.85:
                    logger.warning(f"reject_and_regenerate: attempt {attempt + 1} rejected as duplicate (sim={max_sim:.4f})")
                    continue

            question_data = candidate_data
            break
        except Exception as e:
            logger.error(f"reject_and_regenerate: generation attempt {attempt + 1} failed: {e}")

    if not question_data:
        question.is_latest = True
        question.vetting_status = "rejected"
        await db.commit()
        return {
            "message": "Question rejected (could not generate non-duplicate replacement)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 7. Reuse the original question's session so the regen appears in the same history entry.
    #    If the question has no session (e.g. subject-level gen), create a new one as fallback.
    session_id_to_use = question.session_id
    if not session_id_to_use:
        fallback_session = GenerationSession(
            user_id=teacher_id,
            document_id=document_id,
            subject_id=question.subject_id,
            topic_id=question.topic_id,
            generation_method="vetter_regen",
            requested_count=1,
            status="completed",
            started_at=datetime.now(timezone.utc),
            completed_at=datetime.now(timezone.utc),
            questions_generated=1,
            generation_config={
                "vetted_by": str(current_user.id),
                "original_question_id": str(question_id),
            },
        )
        db.add(fallback_session)
        await db.flush()
        session_id_to_use = fallback_session.id
    # NOTE: Do NOT increment questions_generated — the vetter replacement is a 1-for-1 swap,
    # not a new generation. Bumping the count inflates the teacher's history totals.

    # 8. Save the new question
    try:
        new_question, _ = await gen_service._save_question(
            document_id=document_id,
            session_id=session_id_to_use,
            question_data=question_data,
            question_type=question.question_type,
            marks=question.marks,
            difficulty=question.difficulty_level or "medium",
            chunk_ids=[c.id for c in selected_chunks],
            chunks=selected_chunks,
            subject_id=question.subject_id,
            topic_id=question.topic_id,
        )
    except Exception as e:
        logger.error(f"reject_and_regenerate: save failed: {e}")
        await db.rollback()
        # Re-fetch and restore the original question
        fresh_result = await db.execute(select(Question).where(Question.id == question_id))
        fresh_q = fresh_result.scalar_one_or_none()
        if fresh_q:
            fresh_q.is_latest = True
            fresh_q.vetting_status = "rejected"
            fresh_q.vetted_at = datetime.now(timezone.utc)
            fresh_q.vetted_by = current_user.id
            fresh_q.vetting_notes = rejection_notes or None
            await db.commit()
        return {
            "message": "Question rejected (failed to save regenerated question)",
            "question_id": str(question_id),
            "status": "rejected",
            "regenerated": False,
        }

    # 9. Link the new question as the replacement
    new_question.replaces_id = question_id
    new_question.version_number = (question.version_number or 1) + 1
    new_question.is_latest = True
    new_question.vetting_status = "pending"
    new_question.generation_metadata = {
        **(new_question.generation_metadata or {}),
        "regenerated_by_vetter": True,
        "original_question_id": str(question_id),
        "vetted_by": str(current_user.id),
    }

    # 10. Update replaced_by on the original (now done after we have new_question.id)
    question.replaced_by_id = new_question.id

    await db.commit()
    await db.refresh(new_question)

    logger.info(
        f"reject_and_regenerate: question {question_id} rejected by {current_user.id}, "
        f"new question {new_question.id} created for teacher {teacher_id}"
    )

    # Build source_info for the response from generation_metadata
    new_source_info = None
    gen_meta = new_question.generation_metadata or {}
    if "source_info" in gen_meta:
        meta_si = gen_meta["source_info"]
        if meta_si and meta_si.get("sources"):
            new_source_info = QuestionSourceInfo(
                sources=[SourceReference(**s) for s in meta_si["sources"]],
                generation_reasoning=meta_si.get("generation_reasoning"),
                content_coverage=meta_si.get("content_coverage"),
            ).model_dump()

    return {
        "message": "Question rejected and regenerated successfully",
        "question_id": str(question_id),
        "status": "rejected",
        "regenerated": True,
        "new_question": {
            "id": str(new_question.id),
            "question_text": new_question.question_text,
            "question_type": new_question.question_type,
            "options": new_question.options,
            "correct_answer": new_question.correct_answer,
            "marks": new_question.marks,
            "difficulty_level": new_question.difficulty_level,
            "bloom_taxonomy_level": new_question.bloom_taxonomy_level,
            "vetting_status": new_question.vetting_status,
            "version_number": new_question.version_number,
            "session_id": str(new_question.session_id),
            "source_info": new_source_info,
        },
    }


class VetterUpdateQuestionRequest(BaseModel):
    """Request body for vetter to update a question."""
    marks: Optional[int] = None
    difficulty_level: Optional[str] = None
    bloom_taxonomy_level: Optional[str] = None
    correct_answer: Optional[str] = None
    options: Optional[List[str]] = None
    question_text: Optional[str] = None
    course_outcome_mapping: Optional[dict] = None
    learning_outcome_id: Optional[str] = None


# ============== Version History ==============


@router.get("/questions/{question_id}/version-history")
async def get_question_version_history(
    question_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Get all versions in a question's regeneration chain, ordered oldest-first.
    """
    import logging
    logger = logging.getLogger(__name__)

    # Ensure the question exists
    result = await db.execute(select(Question).where(Question.id == question_id))
    question = result.scalar_one_or_none()
    if not question:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")

    # Walk backwards to find the root version
    seen: set = set()
    current_q = question
    while current_q.replaces_id and current_q.replaces_id not in seen:
        seen.add(current_q.id)
        prev_result = await db.execute(select(Question).where(Question.id == current_q.replaces_id))
        prev_q = prev_result.scalar_one_or_none()
        if not prev_q:
            break
        current_q = prev_q

    # Walk forward from root to collect chain
    versions = []
    chain_seen: set = set()
    q = current_q
    while q and q.id not in chain_seen:
        chain_seen.add(q.id)
        versions.append(q)
        if not q.replaced_by_id:
            break
        next_result = await db.execute(select(Question).where(Question.id == q.replaced_by_id))
        q = next_result.scalar_one_or_none()

    return {
        "question_id": str(question_id),
        "versions": [
            {
                "id": str(v.id),
                "version_number": v.version_number or 1,
                "question_text": v.question_text,
                "question_type": v.question_type,
                "options": v.options,
                "correct_answer": v.correct_answer,
                "marks": v.marks,
                "difficulty_level": v.difficulty_level,
                "vetting_status": v.vetting_status,
                "vetting_notes": v.vetting_notes,
                "is_latest": v.is_latest,
                "generated_at": v.generated_at.isoformat() if v.generated_at else None,
            }
            for v in versions
        ],
    }


# ============== Restore Version ==============


@router.post("/questions/{question_id}/restore")
async def restore_question_version(
    question_id: uuid.UUID,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Restore a previous version by making it the latest active version.
    All other versions in the same chain are demoted to is_latest=False.
    The restored version's vetting_status is reset to 'pending'.
    """
    import logging
    logger = logging.getLogger(__name__)

    # Get the target version
    result = await db.execute(select(Question).where(Question.id == question_id))
    target = result.scalar_one_or_none()
    if not target:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question version not found")

    # Collect all chain IDs by walking backwards and forwards
    chain_ids: set = set()
    # Walk backwards
    current_q = target
    while current_q:
        chain_ids.add(current_q.id)
        if current_q.replaces_id and current_q.replaces_id not in chain_ids:
            prev_result = await db.execute(select(Question).where(Question.id == current_q.replaces_id))
            current_q = prev_result.scalar_one_or_none()
        else:
            break
    # Walk forwards from target
    current_q = target
    while current_q:
        chain_ids.add(current_q.id)
        if current_q.replaced_by_id and current_q.replaced_by_id not in chain_ids:
            next_result = await db.execute(select(Question).where(Question.id == current_q.replaced_by_id))
            current_q = next_result.scalar_one_or_none()
        else:
            break

    # Set all chain members to is_latest=False
    chain_result = await db.execute(select(Question).where(Question.id.in_(list(chain_ids))))
    for q in chain_result.scalars().all():
        q.is_latest = False

    # Promote the target version
    target.is_latest = True
    target.vetting_status = "pending"
    target.vetting_notes = f"Restored from version history by vetter"

    await db.commit()
    await db.refresh(target)
    logger.info(f"Question version {question_id} restored as latest by vetter {current_user.id}")

    return {
        "message": "Version restored successfully",
        "restored_question_id": str(question_id),
        "version_number": target.version_number or 1,
    }





@router.put("/questions/{question_id}", response_model=dict)
async def update_question_as_vetter(
    question_id: uuid.UUID,
    update_data: VetterUpdateQuestionRequest,
    current_user: User = Depends(get_current_vetter),
    db: AsyncSession = Depends(get_db),
):
    """
    Update a question as a vetter.
    Vetters can edit marks, difficulty, answers, and mappings.
    """
    # Get question
    result = await db.execute(
        select(Question)
        .options(
            selectinload(Question.subject),
            selectinload(Question.topic),
        )
        .where(
            Question.id == question_id,
            Question.is_latest == True,
            Question.is_archived == False,
        )
    )
    question = result.scalar_one_or_none()
    
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Question not found",
        )
    
    # Update fields if provided
    if update_data.marks is not None:
        question.marks = update_data.marks
    if update_data.difficulty_level is not None:
        question.difficulty_level = update_data.difficulty_level
    if update_data.bloom_taxonomy_level is not None:
        question.bloom_taxonomy_level = update_data.bloom_taxonomy_level
    if update_data.correct_answer is not None:
        question.correct_answer = update_data.correct_answer
    if update_data.options is not None:
        question.options = update_data.options
    if update_data.question_text is not None:
        question.question_text = update_data.question_text
    if update_data.course_outcome_mapping is not None:
        question.course_outcome_mapping = update_data.course_outcome_mapping
    if update_data.learning_outcome_id is not None:
        question.learning_outcome_id = update_data.learning_outcome_id
    
    await db.commit()
    await db.refresh(question)
    
    return {
        "message": "Question updated successfully",
        "question_id": str(question_id),
        "question": {
            "id": str(question.id),
            "question_text": question.question_text,
            "question_type": question.question_type,
            "options": question.options,
            "correct_answer": question.correct_answer,
            "marks": question.marks,
            "difficulty_level": question.difficulty_level,
            "bloom_taxonomy_level": question.bloom_taxonomy_level,
            "course_outcome_mapping": question.course_outcome_mapping,
            "learning_outcome_id": question.learning_outcome_id,
            "vetting_status": question.vetting_status,
        },
    }
